/* postivoService.h
   Generated by wsdl2h 1.2.13 from https://api.postivo.pl/webservices.php?wsdl and typemap.dat
   2011-02-27 12:24:56 GMT
   gSOAP XML Web services tools.
   Copyright (C) 2001-2009 Robert van Engelen, Genivia Inc. All Rights Reserved.
   Part of this software is released under one of the following licenses:
   GPL or Genivia's license for commercial use.
*/

/* NOTE:

 - Compile this file with soapcpp2 to complete the code generation process.
 - Use soapcpp2 option -I to specify paths for #import
   To build with STL, 'stlvector.h' is imported from 'import' dir in package.
 - Use wsdl2h options -c and -s to generate pure C code or C++ code without STL.
 - Use 'typemap.dat' to control namespace bindings and type mappings.
   It is strongly recommended to customize the names of the namespace prefixes
   generated by wsdl2h. To do so, modify the prefix bindings in the Namespaces
   section below and add the modified lines to 'typemap.dat' to rerun wsdl2h.
 - Use Doxygen (www.doxygen.org) to browse this file.
 - Use wsdl2h option -l to view the software license terms.

   DO NOT include this file directly into your project.
   Include only the soapcpp2-generated headers and source code files.
*/

//gsoapopt cw

/******************************************************************************\
 *                                                                            *
 * http://api.postivo.pl/webservices.php                                      *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Import                                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Schema Namespaces                                                          *
 *                                                                            *
\******************************************************************************/


/* NOTE:

It is strongly recommended to customize the names of the namespace prefixes
generated by wsdl2h. To do so, modify the prefix bindings below and add the
modified lines to typemap.dat to rerun wsdl2h:

ns1 = "http://api.postivo.pl/webservices.php"

*/

//gsoap ns1   schema namespace:	http://api.postivo.pl/webservices.php
//gsoap ns1   schema form:	unqualified

/******************************************************************************\
 *                                                                            *
 * Schema Types                                                               *
 *                                                                            *
\******************************************************************************/


/// Built-in type "xs:boolean".
enum xsd__boolean { xsd__boolean__false_, xsd__boolean__true_ };


/// "http://api.postivo.pl/webservices.php":DocumentFile is a complexType.
struct ns1__DocumentFile
{
/// Element file_stream of type xs:string.
    char*                                file_USCOREstream              1;	///< Required element.
/// Element file_name of type xs:string.
    char*                                file_USCOREname                1;	///< Required element.
};

/// "http://api.postivo.pl/webservices.php":Recipient is a complexType.
struct ns1__Recipient
{
/// Element source of type xs:string.
    char*                                source                        ;	///< Nullable pointer.
/// Element id of type xs:int.
    int*                                 id                            ;	///< Nullable pointer.
/// Element recipient_name of type xs:string.
    char*                                recipient_USCOREname          ;	///< Nullable pointer.
/// Element recipient_address_prefix of type xs:string.
    char*                                recipient_USCOREaddress_USCOREprefix;	///< Nullable pointer.
/// Element recipient_address of type xs:string.
    char*                                recipient_USCOREaddress       ;	///< Nullable pointer.
/// Element recipient_home_number of type xs:string.
    char*                                recipient_USCOREhome_USCOREnumber;	///< Nullable pointer.
/// Element recipient_flat_number of type xs:string.
    char*                                recipient_USCOREflat_USCOREnumber;	///< Nullable pointer.
/// Element recipient_post_code of type xs:string.
    char*                                recipient_USCOREpost_USCOREcode;	///< Nullable pointer.
/// Element recipient_city of type xs:string.
    char*                                recipient_USCOREcity          ;	///< Nullable pointer.
/// Element recipient_country of type xs:string.
    char*                                recipient_USCOREcountry       ;	///< Nullable pointer.
/// Element recipient_fax_number of type xs:string.
    char*                                recipient_USCOREfax_USCOREnumber;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":Option is a complexType.
struct ns1__Option
{
/// Element name of type xs:string.
    char*                                name                           1;	///< Required element.
/// Element value of type xs:string.
    char*                                value                          1;	///< Required element.
};

/// "http://api.postivo.pl/webservices.php":Shipment is a complexType.
struct ns1__Shipment
{
/// Element id of type xs:string.
    char*                                id                             0;	///< Nullable pointer.
/// Element custom_id of type xs:string.
    char*                                custom_USCOREid                0;	///< Nullable pointer.
/// Element recipient_name of type xs:string.
    char*                                recipient_USCOREname           0;	///< Nullable pointer.
/// Element recipient_address of type xs:string.
    char*                                recipient_USCOREaddress        0;	///< Nullable pointer.
/// Element recipient_home_number of type xs:string.
    char*                                recipient_USCOREhome_USCOREnumber 0;	///< Nullable pointer.
/// Element recipient_flat_number of type xs:string.
    char*                                recipient_USCOREflat_USCOREnumber 0;	///< Nullable pointer.
/// Element recipient_post_code of type xs:string.
    char*                                recipient_USCOREpost_USCOREcode 0;	///< Nullable pointer.
/// Element recipient_city of type xs:string.
    char*                                recipient_USCOREcity           0;	///< Nullable pointer.
/// Element recipient_country of type xs:string.
    char*                                recipient_USCOREcountry        0;	///< Nullable pointer.
/// Element recipient_fax_number of type xs:string.
    char*                                recipient_USCOREfax_USCOREnumber 0;	///< Nullable pointer.
/// Element dispatch_carrier of type xs:string.
    char*                                dispatch_USCOREcarrier         0;	///< Nullable pointer.
/// Element dispatch_type of type xs:string.
    char*                                dispatch_USCOREtype            0;	///< Nullable pointer.
/// Element page_number of type xs:int.
    int*                                 page_USCOREnumber              0;	///< Nullable pointer.
/// Element price of type xs:float.
    float*                               price                          0;	///< Nullable pointer.
/// Element status of type xs:string.
    char*                                status                         0;	///< Nullable pointer.
/// Element status_code of type xs:string.
    char*                                status_USCOREcode              0;	///< Nullable pointer.
/// Element status_description of type xs:string.
    char*                                status_USCOREdescription       0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":ConfigProfile is a complexType.
struct ns1__ConfigProfile
{
/// Element config_id of type xs:int.
    int*                                 config_USCOREid                0;	///< Nullable pointer.
/// Element config_name of type xs:string.
    char*                                config_USCOREname              0;	///< Nullable pointer.
/// Element paper_type of type xs:string.
    char*                                paper_USCOREtype               0;	///< Nullable pointer.
/// Element paper_print_type of type xs:string.
    char*                                paper_USCOREprint_USCOREtype   0;	///< Nullable pointer.
/// Element envelope_type of type xs:string.
    char*                                envelope_USCOREtype            0;	///< Nullable pointer.
/// Element envelope_template of type xs:string.
    char*                                envelope_USCOREtemplate        0;	///< Nullable pointer.
/// Element envelope_print_type of type xs:string.
    char*                                envelope_USCOREprint_USCOREtype 0;	///< Nullable pointer.
/// Element carrier of type xs:string.
    char*                                carrier                        0;	///< Nullable pointer.
/// Element dispatch_type of type xs:string.
    char*                                dispatch_USCOREtype            0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":Sender is a complexType.
struct ns1__Sender
{
/// Element sender_id of type xs:int.
    int*                                 sender_USCOREid                0;	///< Nullable pointer.
/// Element sender_name of type xs:string.
    char*                                sender_USCOREname              0;	///< Nullable pointer.
/// Element sender_address of type xs:string.
    char*                                sender_USCOREaddress           0;	///< Nullable pointer.
/// Element sender_home_number of type xs:string.
    char*                                sender_USCOREhome_USCOREnumber 0;	///< Nullable pointer.
/// Element sender_flat_number of type xs:string.
    char*                                sender_USCOREflat_USCOREnumber 0;	///< Nullable pointer.
/// Element sender_post_code of type xs:string.
    char*                                sender_USCOREpost_USCOREcode   0;	///< Nullable pointer.
/// Element sender_city of type xs:string.
    char*                                sender_USCOREcity              0;	///< Nullable pointer.
/// Element sender_country of type xs:string.
    char*                                sender_USCOREcountry           0;	///< Nullable pointer.
/// Element sender_fax_number of type xs:string.
    char*                                sender_USCOREfax_USCOREnumber  0;	///< Nullable pointer.
/// Element default of type xs:string.
    char*                                default_                       0;	///< Nullable pointer.
/// Element active of type xs:string.
    char*                                active                         0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":ShipmentPrice is a complexType.
struct ns1__ShipmentPrice
{
/// Element recipient_name of type xs:string.
    char*                                recipient_USCOREname           0;	///< Nullable pointer.
/// Element recipient_address of type xs:string.
    char*                                recipient_USCOREaddress        0;	///< Nullable pointer.
/// Element recipient_home_number of type xs:string.
    char*                                recipient_USCOREhome_USCOREnumber 0;	///< Nullable pointer.
/// Element recipient_flat_number of type xs:string.
    char*                                recipient_USCOREflat_USCOREnumber 0;	///< Nullable pointer.
/// Element recipient_post_code of type xs:string.
    char*                                recipient_USCOREpost_USCOREcode 0;	///< Nullable pointer.
/// Element recipient_city of type xs:string.
    char*                                recipient_USCOREcity           0;	///< Nullable pointer.
/// Element recipient_country of type xs:string.
    char*                                recipient_USCOREcountry        0;	///< Nullable pointer.
/// Element recipient_fax_number of type xs:string.
    char*                                recipient_USCOREfax_USCOREnumber 0;	///< Nullable pointer.
/// Element dispatch_carrier of type xs:string.
    char*                                dispatch_USCOREcarrier         0;	///< Nullable pointer.
/// Element dispatch_type of type xs:string.
    char*                                dispatch_USCOREtype            0;	///< Nullable pointer.
/// Element page_number of type xs:int.
    int*                                 page_USCOREnumber              0;	///< Nullable pointer.
/// Element price of type xs:float.
    float*                               price                          0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":SenderData is a complexType.
struct ns1__SenderData
{
/// Element sender_name of type xs:string.
    char*                                sender_USCOREname              0;	///< Nullable pointer.
/// Element sender_address_prefix of type xs:string.
    char*                                sender_USCOREaddress_USCOREprefix 0;	///< Nullable pointer.
/// Element sender_address of type xs:string.
    char*                                sender_USCOREaddress           0;	///< Nullable pointer.
/// Element sender_home_number of type xs:string.
    char*                                sender_USCOREhome_USCOREnumber 0;	///< Nullable pointer.
/// Element sender_flat_number of type xs:string.
    char*                                sender_USCOREflat_USCOREnumber 0;	///< Nullable pointer.
/// Element sender_post_code of type xs:string.
    char*                                sender_USCOREpost_USCOREcode   0;	///< Nullable pointer.
/// Element sender_city of type xs:string.
    char*                                sender_USCOREcity              0;	///< Nullable pointer.
/// Element sender_country of type xs:string.
    char*                                sender_USCOREcountry           0;	///< Nullable pointer.
/// Element sender_fax_number of type xs:string.
    char*                                sender_USCOREfax_USCOREnumber  0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":DispatchReturnObject is a complexType.
struct ns1__DispatchReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
/// Element shipments of type "http://api.postivo.pl/webservices.php":ArrayOfShipments.
    struct ArrayOfShipments*             shipments                      1;	///< Required element.
};

/// "http://api.postivo.pl/webservices.php":BalanceReturnObject is a complexType.
struct ns1__BalanceReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
/// Element balance of type xs:float.
    float*                               balance                        0;	///< Nullable pointer.
/// Element limit of type xs:float.
    float*                               limit                          0;	///< Nullable pointer.
/// Element postpaid of type xs:int.
    int*                                 postpaid                       0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":ConfigProfilesReturnObject is a complexType.
struct ns1__ConfigProfilesReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
/// Element config_profiles of type "http://api.postivo.pl/webservices.php":ArrayOfConfigProfiles.
    struct ArrayOfConfigProfiles*        config_USCOREprofiles          0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":SendersReturnObject is a complexType.
struct ns1__SendersReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
/// Element senders of type "http://api.postivo.pl/webservices.php":ArrayOfSenders.
    struct ArrayOfSenders*               senders                        0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":CertificateReturnObject is a complexType.
struct ns1__CertificateReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
/// Element cert_available of type xs:boolean.
    enum xsd__boolean                    cert_USCOREavailable           1;	///< Required element.
/// Element cert_content of type xs:string.
    char*                                cert_USCOREcontent             0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":PriceReturnObject is a complexType.
struct ns1__PriceReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
/// Element shipments_price of type "http://api.postivo.pl/webservices.php":ArrayOfShipmentsPrice.
    struct ArrayOfShipmentsPrice*        shipments_USCOREprice          1;	///< Required element.
};

/// "http://api.postivo.pl/webservices.php":AddSenderReturnObject is a complexType.
struct ns1__AddSenderReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
/// Element sender_id of type xs:int.
    int*                                 sender_USCOREid                0;	///< Nullable pointer.
/// Element shipment_id of type xs:string.
    char*                                shipment_USCOREid              0;	///< Nullable pointer.
/// Element sender_name of type xs:string.
    char*                                sender_USCOREname              0;	///< Nullable pointer.
/// Element sender_address of type xs:string.
    char*                                sender_USCOREaddress           0;	///< Nullable pointer.
/// Element sender_home_number of type xs:string.
    char*                                sender_USCOREhome_USCOREnumber 0;	///< Nullable pointer.
/// Element sender_flat_number of type xs:string.
    char*                                sender_USCOREflat_USCOREnumber 0;	///< Nullable pointer.
/// Element sender_post_code of type xs:string.
    char*                                sender_USCOREpost_USCOREcode   0;	///< Nullable pointer.
/// Element sender_city of type xs:string.
    char*                                sender_USCOREcity              0;	///< Nullable pointer.
/// Element sender_country of type xs:string.
    char*                                sender_USCOREcountry           0;	///< Nullable pointer.
/// Element sender_fax_number of type xs:string.
    char*                                sender_USCOREfax_USCOREnumber  0;	///< Nullable pointer.
};

/// "http://api.postivo.pl/webservices.php":VerifySenderReturnObject is a complexType.
struct ns1__VerifySenderReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
};

/// "http://api.postivo.pl/webservices.php":RemoveSenderReturnObject is a complexType.
struct ns1__RemoveSenderReturnObject
{
/// Element result of type xs:string.
    char*                                result                         1;	///< Required element.
/// Element result_code of type xs:string.
    char*                                result_USCOREcode              1;	///< Required element.
/// Element result_description of type xs:string.
    char*                                result_USCOREdescription       1;	///< Required element.
};

/// "http://api.postivo.pl/webservices.php":ArrayOfDocumentFiles is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://api.postivo.pl/webservices.php":DocumentFile
struct ArrayOfDocumentFiles
{
/// Pointer to array of struct ns1__DocumentFile*.
    struct ns1__DocumentFile*           *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "http://api.postivo.pl/webservices.php":ArrayOfRecipients is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://api.postivo.pl/webservices.php":Recipient
struct ArrayOfRecipients
{
/// Pointer to array of struct ns1__Recipient*.
    struct ns1__Recipient*              *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
    int                                  __offset                      1;
};

/// "http://api.postivo.pl/webservices.php":ArrayOfOptions is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://api.postivo.pl/webservices.php":Option
struct ArrayOfOptions
{
/// Pointer to array of struct ns1__Option*.
    struct ns1__Option*                 *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "http://api.postivo.pl/webservices.php":ArrayOfShipments is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://api.postivo.pl/webservices.php":Shipment
struct ArrayOfShipments
{
/// Pointer to array of struct ns1__Shipment*.
    struct ns1__Shipment*               *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "http://api.postivo.pl/webservices.php":ArrayOfDispatchIds is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of xs:string
struct ArrayOfDispatchIds
{
/// Pointer to array of char*.
    char*                               *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "http://api.postivo.pl/webservices.php":ArrayOfConfigProfiles is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://api.postivo.pl/webservices.php":ConfigProfile
struct ArrayOfConfigProfiles
{
/// Pointer to array of struct ns1__ConfigProfile*.
    struct ns1__ConfigProfile*          *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "http://api.postivo.pl/webservices.php":ArrayOfSenders is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://api.postivo.pl/webservices.php":Sender
struct ArrayOfSenders
{
/// Pointer to array of struct ns1__Sender*.
    struct ns1__Sender*                 *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/// "http://api.postivo.pl/webservices.php":ArrayOfShipmentsPrice is a complexType with complexContent restriction of SOAP-ENC:Array.
/// SOAP encoded array of "http://api.postivo.pl/webservices.php":ShipmentPrice
struct ArrayOfShipmentsPrice
{
/// Pointer to array of struct ns1__ShipmentPrice*.
    struct ns1__ShipmentPrice*          *__ptr                         ;
/// Size of the dynamic array.
    int                                  __size                        ;
/// Offset for partially transmitted arrays (uncomment only when required).
//  int                                  __offset                      ;
};

/******************************************************************************\
 *                                                                            *
 * Services                                                                   *
 *                                                                            *
\******************************************************************************/


//gsoap ns2  service name:	Postivo_x002eplBinding 
//gsoap ns2  service type:	Postivo_x002eplPortType 
//gsoap ns2  service port:	https://api.postivo.pl:443/webservices.php 
//gsoap ns2  service namespace:	http://api.postivo.pl 
//gsoap ns2  service transport:	http://schemas.xmlsoap.org/soap/http 

/** @mainpage Service Definitions

@section Service_bindings Bindings
  - @ref Postivo_x002eplBinding

*/

/**

@page Postivo_x002eplBinding Binding "Postivo_x002eplBinding"

@section Postivo_x002eplBinding_operations Operations of Binding  "Postivo_x002eplBinding"
  - @ref ns2__dispatch
  - @ref ns2__getDispatchStatus
  - @ref ns2__getBalance
  - @ref ns2__getConfigProfiles
  - @ref ns2__getSenders
  - @ref ns2__getCertificate
  - @ref ns2__getPrice
  - @ref ns2__addSender
  - @ref ns2__verifySender
  - @ref ns2__removeSender

@section Postivo_x002eplBinding_ports Endpoints of Binding  "Postivo_x002eplBinding"
  - https://api.postivo.pl:443/webservices.php

Note: use wsdl2h option -N to change the service binding prefix name

*/

/******************************************************************************\
 *                                                                            *
 * Postivo_x002eplBinding                                                     *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * ns2__dispatch                                                              *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__dispatchResponse" of service binding "Postivo_x002eplBinding" operation "ns2__dispatch"
struct ns2__dispatchResponse
{
    struct ns1__DispatchReturnObject*   return_;
};

/// Operation "ns2__dispatch" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Przekazuje now przesyk do realizacji
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#dispatch"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__dispatch(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               msg_USCOREtype,
    struct ArrayOfDocumentFiles*        document_USCOREfiles,
    struct ArrayOfRecipients*           recipients,
    struct ArrayOfOptions*              options,
    // response parameters:
    struct ns2__dispatchResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__dispatch(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               msg_USCOREtype,
    struct ArrayOfDocumentFiles*        document_USCOREfiles,
    struct ArrayOfRecipients*           recipients,
    struct ArrayOfOptions*              options,
    // response parameters:
    struct ns2__dispatchResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	dispatch rpc
//gsoap ns2  service method-encoding:	dispatch http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	dispatch http://api.postivo.pl#dispatch
int ns2__dispatch(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    char*                               msg_USCOREtype,	///< Request parameter
    struct ArrayOfDocumentFiles*        document_USCOREfiles,	///< Request parameter
    struct ArrayOfRecipients*           recipients,	///< Request parameter
    struct ArrayOfOptions*              options,	///< Request parameter
    struct ns2__dispatchResponse       *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__getDispatchStatus                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__getDispatchStatusResponse" of service binding "Postivo_x002eplBinding" operation "ns2__getDispatchStatus"
struct ns2__getDispatchStatusResponse
{
    struct ns1__DispatchReturnObject*   return_;
};

/// Operation "ns2__getDispatchStatus" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Przekazuje statusy przesyek o podanych ID
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#getDispatchStatus"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__getDispatchStatus(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    struct ArrayOfDispatchIds*          dispatch_USCOREids,
    // response parameters:
    struct ns2__getDispatchStatusResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__getDispatchStatus(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    struct ArrayOfDispatchIds*          dispatch_USCOREids,
    // response parameters:
    struct ns2__getDispatchStatusResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	getDispatchStatus rpc
//gsoap ns2  service method-encoding:	getDispatchStatus http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	getDispatchStatus http://api.postivo.pl#getDispatchStatus
int ns2__getDispatchStatus(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    struct ArrayOfDispatchIds*          dispatch_USCOREids,	///< Request parameter
    struct ns2__getDispatchStatusResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__getBalance                                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__getBalanceResponse" of service binding "Postivo_x002eplBinding" operation "ns2__getBalance"
struct ns2__getBalanceResponse
{
    struct ns1__BalanceReturnObject*    return_;
};

/// Operation "ns2__getBalance" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Zwraca stan konta i informacje finansowe
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#getBalance"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__getBalance(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    // response parameters:
    struct ns2__getBalanceResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__getBalance(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    // response parameters:
    struct ns2__getBalanceResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	getBalance rpc
//gsoap ns2  service method-encoding:	getBalance http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	getBalance http://api.postivo.pl#getBalance
int ns2__getBalance(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    struct ns2__getBalanceResponse     *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__getConfigProfiles                                                     *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__getConfigProfilesResponse" of service binding "Postivo_x002eplBinding" operation "ns2__getConfigProfiles"
struct ns2__getConfigProfilesResponse
{
    struct ns1__ConfigProfilesReturnObject* return_;
};

/// Operation "ns2__getConfigProfiles" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Zwraca wszystkie profile konfiguracji zapisane na koncie Uytkownika
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#getConfigProfiles"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__getConfigProfiles(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               msg_USCOREtype,
    // response parameters:
    struct ns2__getConfigProfilesResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__getConfigProfiles(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               msg_USCOREtype,
    // response parameters:
    struct ns2__getConfigProfilesResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	getConfigProfiles rpc
//gsoap ns2  service method-encoding:	getConfigProfiles http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	getConfigProfiles http://api.postivo.pl#getConfigProfiles
int ns2__getConfigProfiles(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    char*                               msg_USCOREtype,	///< Request parameter
    struct ns2__getConfigProfilesResponse*	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__getSenders                                                            *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__getSendersResponse" of service binding "Postivo_x002eplBinding" operation "ns2__getSenders"
struct ns2__getSendersResponse
{
    struct ns1__SendersReturnObject*    return_;
};

/// Operation "ns2__getSenders" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Zwraca wszystkich nadawcw skonfigurowanych na koncie Uytkownika
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#getSenders"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__getSenders(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    // response parameters:
    struct ns2__getSendersResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__getSenders(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    // response parameters:
    struct ns2__getSendersResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	getSenders rpc
//gsoap ns2  service method-encoding:	getSenders http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	getSenders http://api.postivo.pl#getSenders
int ns2__getSenders(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    struct ns2__getSendersResponse     *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__getCertificate                                                        *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__getCertificateResponse" of service binding "Postivo_x002eplBinding" operation "ns2__getCertificate"
struct ns2__getCertificateResponse
{
    struct ns1__CertificateReturnObject* return_;
};

/// Operation "ns2__getCertificate" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Generuje potwierdzenia nadania i odbioru przesyek
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#getCertificate"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__getCertificate(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               dispatch_USCOREid,
    int                                 certificate_USCOREtype,
    // response parameters:
    struct ns2__getCertificateResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__getCertificate(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               dispatch_USCOREid,
    int                                 certificate_USCOREtype,
    // response parameters:
    struct ns2__getCertificateResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	getCertificate rpc
//gsoap ns2  service method-encoding:	getCertificate http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	getCertificate http://api.postivo.pl#getCertificate
int ns2__getCertificate(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    char*                               dispatch_USCOREid,	///< Request parameter
    int                                 certificate_USCOREtype,	///< Request parameter
    struct ns2__getCertificateResponse *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__getPrice                                                              *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__getPriceResponse" of service binding "Postivo_x002eplBinding" operation "ns2__getPrice"
struct ns2__getPriceResponse
{
    struct ns1__PriceReturnObject*      return_;
};

/// Operation "ns2__getPrice" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Oblicza cakowity koszt wysania przesyki
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#getPrice"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__getPrice(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               msg_USCOREtype,
    struct ArrayOfDocumentFiles*        document_USCOREfiles,
    struct ArrayOfRecipients*           recipients,
    int                                 config_USCOREid,
    // response parameters:
    struct ns2__getPriceResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__getPrice(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    char*                               msg_USCOREtype,
    struct ArrayOfDocumentFiles*        document_USCOREfiles,
    struct ArrayOfRecipients*           recipients,
    int                                 config_USCOREid,
    // response parameters:
    struct ns2__getPriceResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	getPrice rpc
//gsoap ns2  service method-encoding:	getPrice http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	getPrice http://api.postivo.pl#getPrice
int ns2__getPrice(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    char*                               msg_USCOREtype,	///< Request parameter
    struct ArrayOfDocumentFiles*        document_USCOREfiles,	///< Request parameter
    struct ArrayOfRecipients*           recipients,	///< Request parameter
    int                                 config_USCOREid,	///< Request parameter
    struct ns2__getPriceResponse       *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__addSender                                                             *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__addSenderResponse" of service binding "Postivo_x002eplBinding" operation "ns2__addSender"
struct ns2__addSenderResponse
{
    struct ns1__AddSenderReturnObject*  return_;
};

/// Operation "ns2__addSender" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Dodaje nowego nadawc do listy i wysya list z kodem weryfikacyjnym
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#addSender"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__addSender(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    struct ns1__SenderData*             sender_USCOREdata,
    enum xsd__boolean                   accept_USCOREterms,
    // response parameters:
    struct ns2__addSenderResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__addSender(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    struct ns1__SenderData*             sender_USCOREdata,
    enum xsd__boolean                   accept_USCOREterms,
    // response parameters:
    struct ns2__addSenderResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	addSender rpc
//gsoap ns2  service method-encoding:	addSender http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	addSender http://api.postivo.pl#addSender
int ns2__addSender(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    struct ns1__SenderData*             sender_USCOREdata,	///< Request parameter
    enum xsd__boolean                   accept_USCOREterms,	///< Request parameter
    struct ns2__addSenderResponse      *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__verifySender                                                          *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__verifySenderResponse" of service binding "Postivo_x002eplBinding" operation "ns2__verifySender"
struct ns2__verifySenderResponse
{
    struct ns1__VerifySenderReturnObject* return_;
};

/// Operation "ns2__verifySender" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Przekazuje kod weryfikacyjny w celu weryfikacji danych nadawcy
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#verifySender"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__verifySender(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    int                                 sender_USCOREid,
    char*                               verification_USCOREcode,
    // response parameters:
    struct ns2__verifySenderResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__verifySender(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    int                                 sender_USCOREid,
    char*                               verification_USCOREcode,
    // response parameters:
    struct ns2__verifySenderResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	verifySender rpc
//gsoap ns2  service method-encoding:	verifySender http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	verifySender http://api.postivo.pl#verifySender
int ns2__verifySender(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    int                                 sender_USCOREid,	///< Request parameter
    char*                               verification_USCOREcode,	///< Request parameter
    struct ns2__verifySenderResponse   *	///< Response struct parameter
);

/******************************************************************************\
 *                                                                            *
 * ns2__removeSender                                                          *
 *                                                                            *
\******************************************************************************/

/// Operation response struct "ns2__removeSenderResponse" of service binding "Postivo_x002eplBinding" operation "ns2__removeSender"
struct ns2__removeSenderResponse
{
    struct ns1__RemoveSenderReturnObject* return_;
};

/// Operation "ns2__removeSender" of service binding "Postivo_x002eplBinding"

/**

Operation details:

Usuwa nadawce z listy nadawcow
  - SOAP RPC encodingStyle="http://schemas.xmlsoap.org/soap/encoding/"
  - SOAP action="http://api.postivo.pl#removeSender"

C stub function (defined in soapClient.c[pp] generated by soapcpp2):
@code
  int soap_call_ns2__removeSender(
    struct soap *soap,
    NULL, // char *endpoint = NULL selects default endpoint for this operation
    NULL, // char *action = NULL selects default action for this operation
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    int                                 sender_USCOREid,
    // response parameters:
    struct ns2__removeSenderResponse*
  );
@endcode

C server function (called from the service dispatcher defined in soapServer.c[pp]):
@code
  int ns2__removeSender(
    struct soap *soap,
    // request parameters:
    char*                               login,
    char*                               api_USCOREpass,
    int                                 sender_USCOREid,
    // response parameters:
    struct ns2__removeSenderResponse*
  );
@endcode

*/

//gsoap ns2  service method-style:	removeSender rpc
//gsoap ns2  service method-encoding:	removeSender http://schemas.xmlsoap.org/soap/encoding/
//gsoap ns2  service method-action:	removeSender http://api.postivo.pl#removeSender
int ns2__removeSender(
    char*                               login,	///< Request parameter
    char*                               api_USCOREpass,	///< Request parameter
    int                                 sender_USCOREid,	///< Request parameter
    struct ns2__removeSenderResponse   *	///< Response struct parameter
);

/* End of postivoService.h */
