/* soapH.h
   Generated by gSOAP 2.7.13 from postivoService.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapH_H
#define soapH_H
#include "soapStub.h"
#ifdef __cplusplus
extern "C" {
#endif
#ifndef WITH_NOIDREF
SOAP_FMAC3 void SOAP_FMAC4 soap_markelement(struct soap*, const void*, int);
SOAP_FMAC3 int SOAP_FMAC4 soap_putelement(struct soap*, const void*, const char*, int, int);
SOAP_FMAC3 void *SOAP_FMAC4 soap_getelement(struct soap*, int*);
SOAP_FMAC3 int SOAP_FMAC4 soap_putindependent(struct soap*);
SOAP_FMAC3 int SOAP_FMAC4 soap_getindependent(struct soap*);
#endif
SOAP_FMAC3 int SOAP_FMAC4 soap_ignore_element(struct soap*);

#ifndef SOAP_TYPE_byte
#define SOAP_TYPE_byte (3)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_byte(struct soap*, char *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_byte(struct soap*, const char *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_byte(struct soap*, const char*, int, const char *, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_get_byte(struct soap*, char *, const char*, const char*);
SOAP_FMAC3 char * SOAP_FMAC4 soap_in_byte(struct soap*, const char*, char *, const char*);

#ifndef SOAP_TYPE_int
#define SOAP_TYPE_int (1)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_int(struct soap*, int *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_int(struct soap*, const int *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_int(struct soap*, const char*, int, const int *, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_get_int(struct soap*, int *, const char*, const char*);
SOAP_FMAC3 int * SOAP_FMAC4 soap_in_int(struct soap*, const char*, int *, const char*);

#ifndef SOAP_TYPE_float
#define SOAP_TYPE_float (13)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_float(struct soap*, float *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_float(struct soap*, const float *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_float(struct soap*, const char*, int, const float *, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_get_float(struct soap*, float *, const char*, const char*);
SOAP_FMAC3 float * SOAP_FMAC4 soap_in_float(struct soap*, const char*, float *, const char*);

#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_xsd__boolean(struct soap*, enum xsd__boolean *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_xsd__boolean(struct soap*, const enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_xsd__boolean(struct soap*, const char*, int, const enum xsd__boolean *, const char*);

SOAP_FMAC3S const char* SOAP_FMAC4S soap_xsd__boolean2s(struct soap*, enum xsd__boolean);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_get_xsd__boolean(struct soap*, enum xsd__boolean *, const char*, const char*);
SOAP_FMAC3 enum xsd__boolean * SOAP_FMAC4 soap_in_xsd__boolean(struct soap*, const char*, enum xsd__boolean *, const char*);

SOAP_FMAC3S int SOAP_FMAC4S soap_s2xsd__boolean(struct soap*, const char*, enum xsd__boolean *);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (116)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Fault(struct soap*, const struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Fault(struct soap*, const char*, int, const struct SOAP_ENV__Fault *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_get_SOAP_ENV__Fault(struct soap*, struct SOAP_ENV__Fault *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Fault * SOAP_FMAC4 soap_in_SOAP_ENV__Fault(struct soap*, const char*, struct SOAP_ENV__Fault *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (115)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Reason(struct soap*, const struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Reason(struct soap*, const char*, int, const struct SOAP_ENV__Reason *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_get_SOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason * SOAP_FMAC4 soap_in_SOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (112)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Detail(struct soap*, const struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Detail(struct soap*, const char*, int, const struct SOAP_ENV__Detail *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_get_SOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail * SOAP_FMAC4 soap_in_SOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (110)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Code(struct soap*, const struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Code(struct soap*, const char*, int, const struct SOAP_ENV__Code *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_get_SOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code * SOAP_FMAC4 soap_in_SOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code *, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (109)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_SOAP_ENV__Header(struct soap*, const struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_SOAP_ENV__Header(struct soap*, const char*, int, const struct SOAP_ENV__Header *, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_get_SOAP_ENV__Header(struct soap*, struct SOAP_ENV__Header *, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Header * SOAP_FMAC4 soap_in_SOAP_ENV__Header(struct soap*, const char*, struct SOAP_ENV__Header *, const char*);

#endif

#ifndef SOAP_TYPE_ns2__removeSender
#define SOAP_TYPE_ns2__removeSender (108)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__removeSender(struct soap*, struct ns2__removeSender *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__removeSender(struct soap*, const struct ns2__removeSender *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__removeSender(struct soap*, const struct ns2__removeSender *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__removeSender(struct soap*, const char*, int, const struct ns2__removeSender *, const char*);
SOAP_FMAC3 struct ns2__removeSender * SOAP_FMAC4 soap_get_ns2__removeSender(struct soap*, struct ns2__removeSender *, const char*, const char*);
SOAP_FMAC3 struct ns2__removeSender * SOAP_FMAC4 soap_in_ns2__removeSender(struct soap*, const char*, struct ns2__removeSender *, const char*);

#ifndef SOAP_TYPE_ns2__removeSenderResponse
#define SOAP_TYPE_ns2__removeSenderResponse (104)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__removeSenderResponse(struct soap*, struct ns2__removeSenderResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__removeSenderResponse(struct soap*, const struct ns2__removeSenderResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__removeSenderResponse(struct soap*, const struct ns2__removeSenderResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__removeSenderResponse(struct soap*, const char*, int, const struct ns2__removeSenderResponse *, const char*);
SOAP_FMAC3 struct ns2__removeSenderResponse * SOAP_FMAC4 soap_get_ns2__removeSenderResponse(struct soap*, struct ns2__removeSenderResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__removeSenderResponse * SOAP_FMAC4 soap_in_ns2__removeSenderResponse(struct soap*, const char*, struct ns2__removeSenderResponse *, const char*);

#ifndef SOAP_TYPE_ns2__verifySender
#define SOAP_TYPE_ns2__verifySender (103)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__verifySender(struct soap*, struct ns2__verifySender *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__verifySender(struct soap*, const struct ns2__verifySender *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__verifySender(struct soap*, const struct ns2__verifySender *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__verifySender(struct soap*, const char*, int, const struct ns2__verifySender *, const char*);
SOAP_FMAC3 struct ns2__verifySender * SOAP_FMAC4 soap_get_ns2__verifySender(struct soap*, struct ns2__verifySender *, const char*, const char*);
SOAP_FMAC3 struct ns2__verifySender * SOAP_FMAC4 soap_in_ns2__verifySender(struct soap*, const char*, struct ns2__verifySender *, const char*);

#ifndef SOAP_TYPE_ns2__verifySenderResponse
#define SOAP_TYPE_ns2__verifySenderResponse (99)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__verifySenderResponse(struct soap*, struct ns2__verifySenderResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__verifySenderResponse(struct soap*, const struct ns2__verifySenderResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__verifySenderResponse(struct soap*, const struct ns2__verifySenderResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__verifySenderResponse(struct soap*, const char*, int, const struct ns2__verifySenderResponse *, const char*);
SOAP_FMAC3 struct ns2__verifySenderResponse * SOAP_FMAC4 soap_get_ns2__verifySenderResponse(struct soap*, struct ns2__verifySenderResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__verifySenderResponse * SOAP_FMAC4 soap_in_ns2__verifySenderResponse(struct soap*, const char*, struct ns2__verifySenderResponse *, const char*);

#ifndef SOAP_TYPE_ns2__addSender
#define SOAP_TYPE_ns2__addSender (98)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__addSender(struct soap*, struct ns2__addSender *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__addSender(struct soap*, const struct ns2__addSender *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__addSender(struct soap*, const struct ns2__addSender *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__addSender(struct soap*, const char*, int, const struct ns2__addSender *, const char*);
SOAP_FMAC3 struct ns2__addSender * SOAP_FMAC4 soap_get_ns2__addSender(struct soap*, struct ns2__addSender *, const char*, const char*);
SOAP_FMAC3 struct ns2__addSender * SOAP_FMAC4 soap_in_ns2__addSender(struct soap*, const char*, struct ns2__addSender *, const char*);

#ifndef SOAP_TYPE_ns2__addSenderResponse
#define SOAP_TYPE_ns2__addSenderResponse (93)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__addSenderResponse(struct soap*, struct ns2__addSenderResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__addSenderResponse(struct soap*, const struct ns2__addSenderResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__addSenderResponse(struct soap*, const struct ns2__addSenderResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__addSenderResponse(struct soap*, const char*, int, const struct ns2__addSenderResponse *, const char*);
SOAP_FMAC3 struct ns2__addSenderResponse * SOAP_FMAC4 soap_get_ns2__addSenderResponse(struct soap*, struct ns2__addSenderResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__addSenderResponse * SOAP_FMAC4 soap_in_ns2__addSenderResponse(struct soap*, const char*, struct ns2__addSenderResponse *, const char*);

#ifndef SOAP_TYPE_ns2__getPrice
#define SOAP_TYPE_ns2__getPrice (92)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getPrice(struct soap*, struct ns2__getPrice *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getPrice(struct soap*, const struct ns2__getPrice *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getPrice(struct soap*, const struct ns2__getPrice *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getPrice(struct soap*, const char*, int, const struct ns2__getPrice *, const char*);
SOAP_FMAC3 struct ns2__getPrice * SOAP_FMAC4 soap_get_ns2__getPrice(struct soap*, struct ns2__getPrice *, const char*, const char*);
SOAP_FMAC3 struct ns2__getPrice * SOAP_FMAC4 soap_in_ns2__getPrice(struct soap*, const char*, struct ns2__getPrice *, const char*);

#ifndef SOAP_TYPE_ns2__getPriceResponse
#define SOAP_TYPE_ns2__getPriceResponse (88)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getPriceResponse(struct soap*, struct ns2__getPriceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getPriceResponse(struct soap*, const struct ns2__getPriceResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getPriceResponse(struct soap*, const struct ns2__getPriceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getPriceResponse(struct soap*, const char*, int, const struct ns2__getPriceResponse *, const char*);
SOAP_FMAC3 struct ns2__getPriceResponse * SOAP_FMAC4 soap_get_ns2__getPriceResponse(struct soap*, struct ns2__getPriceResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getPriceResponse * SOAP_FMAC4 soap_in_ns2__getPriceResponse(struct soap*, const char*, struct ns2__getPriceResponse *, const char*);

#ifndef SOAP_TYPE_ns2__getCertificate
#define SOAP_TYPE_ns2__getCertificate (87)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getCertificate(struct soap*, struct ns2__getCertificate *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getCertificate(struct soap*, const struct ns2__getCertificate *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getCertificate(struct soap*, const struct ns2__getCertificate *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getCertificate(struct soap*, const char*, int, const struct ns2__getCertificate *, const char*);
SOAP_FMAC3 struct ns2__getCertificate * SOAP_FMAC4 soap_get_ns2__getCertificate(struct soap*, struct ns2__getCertificate *, const char*, const char*);
SOAP_FMAC3 struct ns2__getCertificate * SOAP_FMAC4 soap_in_ns2__getCertificate(struct soap*, const char*, struct ns2__getCertificate *, const char*);

#ifndef SOAP_TYPE_ns2__getCertificateResponse
#define SOAP_TYPE_ns2__getCertificateResponse (83)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getCertificateResponse(struct soap*, struct ns2__getCertificateResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getCertificateResponse(struct soap*, const struct ns2__getCertificateResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getCertificateResponse(struct soap*, const struct ns2__getCertificateResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getCertificateResponse(struct soap*, const char*, int, const struct ns2__getCertificateResponse *, const char*);
SOAP_FMAC3 struct ns2__getCertificateResponse * SOAP_FMAC4 soap_get_ns2__getCertificateResponse(struct soap*, struct ns2__getCertificateResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getCertificateResponse * SOAP_FMAC4 soap_in_ns2__getCertificateResponse(struct soap*, const char*, struct ns2__getCertificateResponse *, const char*);

#ifndef SOAP_TYPE_ns2__getSenders
#define SOAP_TYPE_ns2__getSenders (82)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getSenders(struct soap*, struct ns2__getSenders *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getSenders(struct soap*, const struct ns2__getSenders *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getSenders(struct soap*, const struct ns2__getSenders *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getSenders(struct soap*, const char*, int, const struct ns2__getSenders *, const char*);
SOAP_FMAC3 struct ns2__getSenders * SOAP_FMAC4 soap_get_ns2__getSenders(struct soap*, struct ns2__getSenders *, const char*, const char*);
SOAP_FMAC3 struct ns2__getSenders * SOAP_FMAC4 soap_in_ns2__getSenders(struct soap*, const char*, struct ns2__getSenders *, const char*);

#ifndef SOAP_TYPE_ns2__getSendersResponse
#define SOAP_TYPE_ns2__getSendersResponse (78)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getSendersResponse(struct soap*, struct ns2__getSendersResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getSendersResponse(struct soap*, const struct ns2__getSendersResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getSendersResponse(struct soap*, const struct ns2__getSendersResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getSendersResponse(struct soap*, const char*, int, const struct ns2__getSendersResponse *, const char*);
SOAP_FMAC3 struct ns2__getSendersResponse * SOAP_FMAC4 soap_get_ns2__getSendersResponse(struct soap*, struct ns2__getSendersResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getSendersResponse * SOAP_FMAC4 soap_in_ns2__getSendersResponse(struct soap*, const char*, struct ns2__getSendersResponse *, const char*);

#ifndef SOAP_TYPE_ns2__getConfigProfiles
#define SOAP_TYPE_ns2__getConfigProfiles (77)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getConfigProfiles(struct soap*, struct ns2__getConfigProfiles *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getConfigProfiles(struct soap*, const struct ns2__getConfigProfiles *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getConfigProfiles(struct soap*, const struct ns2__getConfigProfiles *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getConfigProfiles(struct soap*, const char*, int, const struct ns2__getConfigProfiles *, const char*);
SOAP_FMAC3 struct ns2__getConfigProfiles * SOAP_FMAC4 soap_get_ns2__getConfigProfiles(struct soap*, struct ns2__getConfigProfiles *, const char*, const char*);
SOAP_FMAC3 struct ns2__getConfigProfiles * SOAP_FMAC4 soap_in_ns2__getConfigProfiles(struct soap*, const char*, struct ns2__getConfigProfiles *, const char*);

#ifndef SOAP_TYPE_ns2__getConfigProfilesResponse
#define SOAP_TYPE_ns2__getConfigProfilesResponse (73)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getConfigProfilesResponse(struct soap*, struct ns2__getConfigProfilesResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getConfigProfilesResponse(struct soap*, const struct ns2__getConfigProfilesResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getConfigProfilesResponse(struct soap*, const struct ns2__getConfigProfilesResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getConfigProfilesResponse(struct soap*, const char*, int, const struct ns2__getConfigProfilesResponse *, const char*);
SOAP_FMAC3 struct ns2__getConfigProfilesResponse * SOAP_FMAC4 soap_get_ns2__getConfigProfilesResponse(struct soap*, struct ns2__getConfigProfilesResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getConfigProfilesResponse * SOAP_FMAC4 soap_in_ns2__getConfigProfilesResponse(struct soap*, const char*, struct ns2__getConfigProfilesResponse *, const char*);

#ifndef SOAP_TYPE_ns2__getBalance
#define SOAP_TYPE_ns2__getBalance (72)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getBalance(struct soap*, struct ns2__getBalance *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getBalance(struct soap*, const struct ns2__getBalance *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getBalance(struct soap*, const struct ns2__getBalance *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getBalance(struct soap*, const char*, int, const struct ns2__getBalance *, const char*);
SOAP_FMAC3 struct ns2__getBalance * SOAP_FMAC4 soap_get_ns2__getBalance(struct soap*, struct ns2__getBalance *, const char*, const char*);
SOAP_FMAC3 struct ns2__getBalance * SOAP_FMAC4 soap_in_ns2__getBalance(struct soap*, const char*, struct ns2__getBalance *, const char*);

#ifndef SOAP_TYPE_ns2__getBalanceResponse
#define SOAP_TYPE_ns2__getBalanceResponse (68)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getBalanceResponse(struct soap*, struct ns2__getBalanceResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getBalanceResponse(struct soap*, const struct ns2__getBalanceResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getBalanceResponse(struct soap*, const struct ns2__getBalanceResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getBalanceResponse(struct soap*, const char*, int, const struct ns2__getBalanceResponse *, const char*);
SOAP_FMAC3 struct ns2__getBalanceResponse * SOAP_FMAC4 soap_get_ns2__getBalanceResponse(struct soap*, struct ns2__getBalanceResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getBalanceResponse * SOAP_FMAC4 soap_in_ns2__getBalanceResponse(struct soap*, const char*, struct ns2__getBalanceResponse *, const char*);

#ifndef SOAP_TYPE_ns2__getDispatchStatus
#define SOAP_TYPE_ns2__getDispatchStatus (67)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getDispatchStatus(struct soap*, struct ns2__getDispatchStatus *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getDispatchStatus(struct soap*, const struct ns2__getDispatchStatus *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getDispatchStatus(struct soap*, const struct ns2__getDispatchStatus *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getDispatchStatus(struct soap*, const char*, int, const struct ns2__getDispatchStatus *, const char*);
SOAP_FMAC3 struct ns2__getDispatchStatus * SOAP_FMAC4 soap_get_ns2__getDispatchStatus(struct soap*, struct ns2__getDispatchStatus *, const char*, const char*);
SOAP_FMAC3 struct ns2__getDispatchStatus * SOAP_FMAC4 soap_in_ns2__getDispatchStatus(struct soap*, const char*, struct ns2__getDispatchStatus *, const char*);

#ifndef SOAP_TYPE_ns2__getDispatchStatusResponse
#define SOAP_TYPE_ns2__getDispatchStatusResponse (63)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__getDispatchStatusResponse(struct soap*, struct ns2__getDispatchStatusResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__getDispatchStatusResponse(struct soap*, const struct ns2__getDispatchStatusResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__getDispatchStatusResponse(struct soap*, const struct ns2__getDispatchStatusResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__getDispatchStatusResponse(struct soap*, const char*, int, const struct ns2__getDispatchStatusResponse *, const char*);
SOAP_FMAC3 struct ns2__getDispatchStatusResponse * SOAP_FMAC4 soap_get_ns2__getDispatchStatusResponse(struct soap*, struct ns2__getDispatchStatusResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__getDispatchStatusResponse * SOAP_FMAC4 soap_in_ns2__getDispatchStatusResponse(struct soap*, const char*, struct ns2__getDispatchStatusResponse *, const char*);

#ifndef SOAP_TYPE_ns2__dispatch
#define SOAP_TYPE_ns2__dispatch (62)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__dispatch(struct soap*, struct ns2__dispatch *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__dispatch(struct soap*, const struct ns2__dispatch *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__dispatch(struct soap*, const struct ns2__dispatch *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__dispatch(struct soap*, const char*, int, const struct ns2__dispatch *, const char*);
SOAP_FMAC3 struct ns2__dispatch * SOAP_FMAC4 soap_get_ns2__dispatch(struct soap*, struct ns2__dispatch *, const char*, const char*);
SOAP_FMAC3 struct ns2__dispatch * SOAP_FMAC4 soap_in_ns2__dispatch(struct soap*, const char*, struct ns2__dispatch *, const char*);

#ifndef SOAP_TYPE_ns2__dispatchResponse
#define SOAP_TYPE_ns2__dispatchResponse (55)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns2__dispatchResponse(struct soap*, struct ns2__dispatchResponse *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns2__dispatchResponse(struct soap*, const struct ns2__dispatchResponse *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns2__dispatchResponse(struct soap*, const struct ns2__dispatchResponse *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns2__dispatchResponse(struct soap*, const char*, int, const struct ns2__dispatchResponse *, const char*);
SOAP_FMAC3 struct ns2__dispatchResponse * SOAP_FMAC4 soap_get_ns2__dispatchResponse(struct soap*, struct ns2__dispatchResponse *, const char*, const char*);
SOAP_FMAC3 struct ns2__dispatchResponse * SOAP_FMAC4 soap_in_ns2__dispatchResponse(struct soap*, const char*, struct ns2__dispatchResponse *, const char*);

#ifndef SOAP_TYPE_ArrayOfDispatchIds
#define SOAP_TYPE_ArrayOfDispatchIds (47)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfDispatchIds(struct soap*, struct ArrayOfDispatchIds *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfDispatchIds(struct soap*, struct ArrayOfDispatchIds const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfDispatchIds(struct soap*, const struct ArrayOfDispatchIds *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfDispatchIds(struct soap*, const char*, int, const struct ArrayOfDispatchIds *, const char*);
SOAP_FMAC3 struct ArrayOfDispatchIds * SOAP_FMAC4 soap_get_ArrayOfDispatchIds(struct soap*, struct ArrayOfDispatchIds *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfDispatchIds * SOAP_FMAC4 soap_in_ArrayOfDispatchIds(struct soap*, const char*, struct ArrayOfDispatchIds *, const char*);

#ifndef SOAP_TYPE_ArrayOfOptions
#define SOAP_TYPE_ArrayOfOptions (42)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfOptions(struct soap*, struct ArrayOfOptions *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfOptions(struct soap*, struct ArrayOfOptions const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfOptions(struct soap*, const struct ArrayOfOptions *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfOptions(struct soap*, const char*, int, const struct ArrayOfOptions *, const char*);
SOAP_FMAC3 struct ArrayOfOptions * SOAP_FMAC4 soap_get_ArrayOfOptions(struct soap*, struct ArrayOfOptions *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfOptions * SOAP_FMAC4 soap_in_ArrayOfOptions(struct soap*, const char*, struct ArrayOfOptions *, const char*);

#ifndef SOAP_TYPE_ArrayOfRecipients
#define SOAP_TYPE_ArrayOfRecipients (39)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfRecipients(struct soap*, struct ArrayOfRecipients *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfRecipients(struct soap*, struct ArrayOfRecipients const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfRecipients(struct soap*, const struct ArrayOfRecipients *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfRecipients(struct soap*, const char*, int, const struct ArrayOfRecipients *, const char*);
SOAP_FMAC3 struct ArrayOfRecipients * SOAP_FMAC4 soap_get_ArrayOfRecipients(struct soap*, struct ArrayOfRecipients *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfRecipients * SOAP_FMAC4 soap_in_ArrayOfRecipients(struct soap*, const char*, struct ArrayOfRecipients *, const char*);

#ifndef SOAP_TYPE_ArrayOfDocumentFiles
#define SOAP_TYPE_ArrayOfDocumentFiles (36)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfDocumentFiles(struct soap*, struct ArrayOfDocumentFiles *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfDocumentFiles(struct soap*, struct ArrayOfDocumentFiles const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfDocumentFiles(struct soap*, const struct ArrayOfDocumentFiles *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfDocumentFiles(struct soap*, const char*, int, const struct ArrayOfDocumentFiles *, const char*);
SOAP_FMAC3 struct ArrayOfDocumentFiles * SOAP_FMAC4 soap_get_ArrayOfDocumentFiles(struct soap*, struct ArrayOfDocumentFiles *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfDocumentFiles * SOAP_FMAC4 soap_in_ArrayOfDocumentFiles(struct soap*, const char*, struct ArrayOfDocumentFiles *, const char*);

#ifndef SOAP_TYPE_ns1__RemoveSenderReturnObject
#define SOAP_TYPE_ns1__RemoveSenderReturnObject (35)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__RemoveSenderReturnObject(struct soap*, struct ns1__RemoveSenderReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__RemoveSenderReturnObject(struct soap*, const struct ns1__RemoveSenderReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__RemoveSenderReturnObject(struct soap*, const struct ns1__RemoveSenderReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__RemoveSenderReturnObject(struct soap*, const char*, int, const struct ns1__RemoveSenderReturnObject *, const char*);
SOAP_FMAC3 struct ns1__RemoveSenderReturnObject * SOAP_FMAC4 soap_get_ns1__RemoveSenderReturnObject(struct soap*, struct ns1__RemoveSenderReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__RemoveSenderReturnObject * SOAP_FMAC4 soap_in_ns1__RemoveSenderReturnObject(struct soap*, const char*, struct ns1__RemoveSenderReturnObject *, const char*);

#ifndef SOAP_TYPE_ns1__VerifySenderReturnObject
#define SOAP_TYPE_ns1__VerifySenderReturnObject (34)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__VerifySenderReturnObject(struct soap*, struct ns1__VerifySenderReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__VerifySenderReturnObject(struct soap*, const struct ns1__VerifySenderReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__VerifySenderReturnObject(struct soap*, const struct ns1__VerifySenderReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__VerifySenderReturnObject(struct soap*, const char*, int, const struct ns1__VerifySenderReturnObject *, const char*);
SOAP_FMAC3 struct ns1__VerifySenderReturnObject * SOAP_FMAC4 soap_get_ns1__VerifySenderReturnObject(struct soap*, struct ns1__VerifySenderReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__VerifySenderReturnObject * SOAP_FMAC4 soap_in_ns1__VerifySenderReturnObject(struct soap*, const char*, struct ns1__VerifySenderReturnObject *, const char*);

#ifndef SOAP_TYPE_ns1__AddSenderReturnObject
#define SOAP_TYPE_ns1__AddSenderReturnObject (33)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__AddSenderReturnObject(struct soap*, struct ns1__AddSenderReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__AddSenderReturnObject(struct soap*, const struct ns1__AddSenderReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__AddSenderReturnObject(struct soap*, const struct ns1__AddSenderReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__AddSenderReturnObject(struct soap*, const char*, int, const struct ns1__AddSenderReturnObject *, const char*);
SOAP_FMAC3 struct ns1__AddSenderReturnObject * SOAP_FMAC4 soap_get_ns1__AddSenderReturnObject(struct soap*, struct ns1__AddSenderReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__AddSenderReturnObject * SOAP_FMAC4 soap_in_ns1__AddSenderReturnObject(struct soap*, const char*, struct ns1__AddSenderReturnObject *, const char*);

#ifndef SOAP_TYPE_ArrayOfShipmentsPrice
#define SOAP_TYPE_ArrayOfShipmentsPrice (31)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfShipmentsPrice(struct soap*, struct ArrayOfShipmentsPrice *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfShipmentsPrice(struct soap*, struct ArrayOfShipmentsPrice const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfShipmentsPrice(struct soap*, const struct ArrayOfShipmentsPrice *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfShipmentsPrice(struct soap*, const char*, int, const struct ArrayOfShipmentsPrice *, const char*);
SOAP_FMAC3 struct ArrayOfShipmentsPrice * SOAP_FMAC4 soap_get_ArrayOfShipmentsPrice(struct soap*, struct ArrayOfShipmentsPrice *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfShipmentsPrice * SOAP_FMAC4 soap_in_ArrayOfShipmentsPrice(struct soap*, const char*, struct ArrayOfShipmentsPrice *, const char*);

#ifndef SOAP_TYPE_ns1__PriceReturnObject
#define SOAP_TYPE_ns1__PriceReturnObject (30)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__PriceReturnObject(struct soap*, struct ns1__PriceReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__PriceReturnObject(struct soap*, const struct ns1__PriceReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__PriceReturnObject(struct soap*, const struct ns1__PriceReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__PriceReturnObject(struct soap*, const char*, int, const struct ns1__PriceReturnObject *, const char*);
SOAP_FMAC3 struct ns1__PriceReturnObject * SOAP_FMAC4 soap_get_ns1__PriceReturnObject(struct soap*, struct ns1__PriceReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__PriceReturnObject * SOAP_FMAC4 soap_in_ns1__PriceReturnObject(struct soap*, const char*, struct ns1__PriceReturnObject *, const char*);

#ifndef SOAP_TYPE_ns1__CertificateReturnObject
#define SOAP_TYPE_ns1__CertificateReturnObject (29)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__CertificateReturnObject(struct soap*, struct ns1__CertificateReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__CertificateReturnObject(struct soap*, const struct ns1__CertificateReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__CertificateReturnObject(struct soap*, const struct ns1__CertificateReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__CertificateReturnObject(struct soap*, const char*, int, const struct ns1__CertificateReturnObject *, const char*);
SOAP_FMAC3 struct ns1__CertificateReturnObject * SOAP_FMAC4 soap_get_ns1__CertificateReturnObject(struct soap*, struct ns1__CertificateReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__CertificateReturnObject * SOAP_FMAC4 soap_in_ns1__CertificateReturnObject(struct soap*, const char*, struct ns1__CertificateReturnObject *, const char*);

#ifndef SOAP_TYPE_ArrayOfSenders
#define SOAP_TYPE_ArrayOfSenders (27)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfSenders(struct soap*, struct ArrayOfSenders *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfSenders(struct soap*, struct ArrayOfSenders const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfSenders(struct soap*, const struct ArrayOfSenders *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfSenders(struct soap*, const char*, int, const struct ArrayOfSenders *, const char*);
SOAP_FMAC3 struct ArrayOfSenders * SOAP_FMAC4 soap_get_ArrayOfSenders(struct soap*, struct ArrayOfSenders *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfSenders * SOAP_FMAC4 soap_in_ArrayOfSenders(struct soap*, const char*, struct ArrayOfSenders *, const char*);

#ifndef SOAP_TYPE_ns1__SendersReturnObject
#define SOAP_TYPE_ns1__SendersReturnObject (26)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__SendersReturnObject(struct soap*, struct ns1__SendersReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__SendersReturnObject(struct soap*, const struct ns1__SendersReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__SendersReturnObject(struct soap*, const struct ns1__SendersReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SendersReturnObject(struct soap*, const char*, int, const struct ns1__SendersReturnObject *, const char*);
SOAP_FMAC3 struct ns1__SendersReturnObject * SOAP_FMAC4 soap_get_ns1__SendersReturnObject(struct soap*, struct ns1__SendersReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__SendersReturnObject * SOAP_FMAC4 soap_in_ns1__SendersReturnObject(struct soap*, const char*, struct ns1__SendersReturnObject *, const char*);

#ifndef SOAP_TYPE_ArrayOfConfigProfiles
#define SOAP_TYPE_ArrayOfConfigProfiles (24)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfConfigProfiles(struct soap*, struct ArrayOfConfigProfiles *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfConfigProfiles(struct soap*, struct ArrayOfConfigProfiles const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfConfigProfiles(struct soap*, const struct ArrayOfConfigProfiles *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfConfigProfiles(struct soap*, const char*, int, const struct ArrayOfConfigProfiles *, const char*);
SOAP_FMAC3 struct ArrayOfConfigProfiles * SOAP_FMAC4 soap_get_ArrayOfConfigProfiles(struct soap*, struct ArrayOfConfigProfiles *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfConfigProfiles * SOAP_FMAC4 soap_in_ArrayOfConfigProfiles(struct soap*, const char*, struct ArrayOfConfigProfiles *, const char*);

#ifndef SOAP_TYPE_ns1__ConfigProfilesReturnObject
#define SOAP_TYPE_ns1__ConfigProfilesReturnObject (23)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ConfigProfilesReturnObject(struct soap*, struct ns1__ConfigProfilesReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ConfigProfilesReturnObject(struct soap*, const struct ns1__ConfigProfilesReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ConfigProfilesReturnObject(struct soap*, const struct ns1__ConfigProfilesReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ConfigProfilesReturnObject(struct soap*, const char*, int, const struct ns1__ConfigProfilesReturnObject *, const char*);
SOAP_FMAC3 struct ns1__ConfigProfilesReturnObject * SOAP_FMAC4 soap_get_ns1__ConfigProfilesReturnObject(struct soap*, struct ns1__ConfigProfilesReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__ConfigProfilesReturnObject * SOAP_FMAC4 soap_in_ns1__ConfigProfilesReturnObject(struct soap*, const char*, struct ns1__ConfigProfilesReturnObject *, const char*);

#ifndef SOAP_TYPE_ns1__BalanceReturnObject
#define SOAP_TYPE_ns1__BalanceReturnObject (22)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__BalanceReturnObject(struct soap*, struct ns1__BalanceReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__BalanceReturnObject(struct soap*, const struct ns1__BalanceReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__BalanceReturnObject(struct soap*, const struct ns1__BalanceReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__BalanceReturnObject(struct soap*, const char*, int, const struct ns1__BalanceReturnObject *, const char*);
SOAP_FMAC3 struct ns1__BalanceReturnObject * SOAP_FMAC4 soap_get_ns1__BalanceReturnObject(struct soap*, struct ns1__BalanceReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__BalanceReturnObject * SOAP_FMAC4 soap_in_ns1__BalanceReturnObject(struct soap*, const char*, struct ns1__BalanceReturnObject *, const char*);

#ifndef SOAP_TYPE_ArrayOfShipments
#define SOAP_TYPE_ArrayOfShipments (20)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ArrayOfShipments(struct soap*, struct ArrayOfShipments *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ArrayOfShipments(struct soap*, struct ArrayOfShipments const*);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ArrayOfShipments(struct soap*, const struct ArrayOfShipments *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ArrayOfShipments(struct soap*, const char*, int, const struct ArrayOfShipments *, const char*);
SOAP_FMAC3 struct ArrayOfShipments * SOAP_FMAC4 soap_get_ArrayOfShipments(struct soap*, struct ArrayOfShipments *, const char*, const char*);
SOAP_FMAC3 struct ArrayOfShipments * SOAP_FMAC4 soap_in_ArrayOfShipments(struct soap*, const char*, struct ArrayOfShipments *, const char*);

#ifndef SOAP_TYPE_ns1__DispatchReturnObject
#define SOAP_TYPE_ns1__DispatchReturnObject (19)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__DispatchReturnObject(struct soap*, struct ns1__DispatchReturnObject *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__DispatchReturnObject(struct soap*, const struct ns1__DispatchReturnObject *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__DispatchReturnObject(struct soap*, const struct ns1__DispatchReturnObject *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DispatchReturnObject(struct soap*, const char*, int, const struct ns1__DispatchReturnObject *, const char*);
SOAP_FMAC3 struct ns1__DispatchReturnObject * SOAP_FMAC4 soap_get_ns1__DispatchReturnObject(struct soap*, struct ns1__DispatchReturnObject *, const char*, const char*);
SOAP_FMAC3 struct ns1__DispatchReturnObject * SOAP_FMAC4 soap_in_ns1__DispatchReturnObject(struct soap*, const char*, struct ns1__DispatchReturnObject *, const char*);

#ifndef SOAP_TYPE_ns1__SenderData
#define SOAP_TYPE_ns1__SenderData (18)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__SenderData(struct soap*, struct ns1__SenderData *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__SenderData(struct soap*, const struct ns1__SenderData *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__SenderData(struct soap*, const struct ns1__SenderData *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__SenderData(struct soap*, const char*, int, const struct ns1__SenderData *, const char*);
SOAP_FMAC3 struct ns1__SenderData * SOAP_FMAC4 soap_get_ns1__SenderData(struct soap*, struct ns1__SenderData *, const char*, const char*);
SOAP_FMAC3 struct ns1__SenderData * SOAP_FMAC4 soap_in_ns1__SenderData(struct soap*, const char*, struct ns1__SenderData *, const char*);

#ifndef SOAP_TYPE_ns1__ShipmentPrice
#define SOAP_TYPE_ns1__ShipmentPrice (17)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ShipmentPrice(struct soap*, const struct ns1__ShipmentPrice *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ShipmentPrice(struct soap*, const struct ns1__ShipmentPrice *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ShipmentPrice(struct soap*, const char*, int, const struct ns1__ShipmentPrice *, const char*);
SOAP_FMAC3 struct ns1__ShipmentPrice * SOAP_FMAC4 soap_get_ns1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice *, const char*, const char*);
SOAP_FMAC3 struct ns1__ShipmentPrice * SOAP_FMAC4 soap_in_ns1__ShipmentPrice(struct soap*, const char*, struct ns1__ShipmentPrice *, const char*);

#ifndef SOAP_TYPE_ns1__Sender
#define SOAP_TYPE_ns1__Sender (16)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__Sender(struct soap*, struct ns1__Sender *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__Sender(struct soap*, const struct ns1__Sender *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__Sender(struct soap*, const struct ns1__Sender *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Sender(struct soap*, const char*, int, const struct ns1__Sender *, const char*);
SOAP_FMAC3 struct ns1__Sender * SOAP_FMAC4 soap_get_ns1__Sender(struct soap*, struct ns1__Sender *, const char*, const char*);
SOAP_FMAC3 struct ns1__Sender * SOAP_FMAC4 soap_in_ns1__Sender(struct soap*, const char*, struct ns1__Sender *, const char*);

#ifndef SOAP_TYPE_ns1__ConfigProfile
#define SOAP_TYPE_ns1__ConfigProfile (15)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__ConfigProfile(struct soap*, struct ns1__ConfigProfile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__ConfigProfile(struct soap*, const struct ns1__ConfigProfile *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__ConfigProfile(struct soap*, const struct ns1__ConfigProfile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__ConfigProfile(struct soap*, const char*, int, const struct ns1__ConfigProfile *, const char*);
SOAP_FMAC3 struct ns1__ConfigProfile * SOAP_FMAC4 soap_get_ns1__ConfigProfile(struct soap*, struct ns1__ConfigProfile *, const char*, const char*);
SOAP_FMAC3 struct ns1__ConfigProfile * SOAP_FMAC4 soap_in_ns1__ConfigProfile(struct soap*, const char*, struct ns1__ConfigProfile *, const char*);

#ifndef SOAP_TYPE_ns1__Shipment
#define SOAP_TYPE_ns1__Shipment (12)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__Shipment(struct soap*, struct ns1__Shipment *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__Shipment(struct soap*, const struct ns1__Shipment *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__Shipment(struct soap*, const struct ns1__Shipment *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Shipment(struct soap*, const char*, int, const struct ns1__Shipment *, const char*);
SOAP_FMAC3 struct ns1__Shipment * SOAP_FMAC4 soap_get_ns1__Shipment(struct soap*, struct ns1__Shipment *, const char*, const char*);
SOAP_FMAC3 struct ns1__Shipment * SOAP_FMAC4 soap_in_ns1__Shipment(struct soap*, const char*, struct ns1__Shipment *, const char*);

#ifndef SOAP_TYPE_ns1__Option
#define SOAP_TYPE_ns1__Option (11)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__Option(struct soap*, struct ns1__Option *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__Option(struct soap*, const struct ns1__Option *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__Option(struct soap*, const struct ns1__Option *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Option(struct soap*, const char*, int, const struct ns1__Option *, const char*);
SOAP_FMAC3 struct ns1__Option * SOAP_FMAC4 soap_get_ns1__Option(struct soap*, struct ns1__Option *, const char*, const char*);
SOAP_FMAC3 struct ns1__Option * SOAP_FMAC4 soap_in_ns1__Option(struct soap*, const char*, struct ns1__Option *, const char*);

#ifndef SOAP_TYPE_ns1__Recipient
#define SOAP_TYPE_ns1__Recipient (9)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__Recipient(struct soap*, struct ns1__Recipient *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__Recipient(struct soap*, const struct ns1__Recipient *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__Recipient(struct soap*, const struct ns1__Recipient *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__Recipient(struct soap*, const char*, int, const struct ns1__Recipient *, const char*);
SOAP_FMAC3 struct ns1__Recipient * SOAP_FMAC4 soap_get_ns1__Recipient(struct soap*, struct ns1__Recipient *, const char*, const char*);
SOAP_FMAC3 struct ns1__Recipient * SOAP_FMAC4 soap_in_ns1__Recipient(struct soap*, const char*, struct ns1__Recipient *, const char*);

#ifndef SOAP_TYPE_ns1__DocumentFile
#define SOAP_TYPE_ns1__DocumentFile (8)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_ns1__DocumentFile(struct soap*, struct ns1__DocumentFile *);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_ns1__DocumentFile(struct soap*, const struct ns1__DocumentFile *);

SOAP_FMAC3 int SOAP_FMAC4 soap_put_ns1__DocumentFile(struct soap*, const struct ns1__DocumentFile *, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_ns1__DocumentFile(struct soap*, const char*, int, const struct ns1__DocumentFile *, const char*);
SOAP_FMAC3 struct ns1__DocumentFile * SOAP_FMAC4 soap_get_ns1__DocumentFile(struct soap*, struct ns1__DocumentFile *, const char*, const char*);
SOAP_FMAC3 struct ns1__DocumentFile * SOAP_FMAC4 soap_in_ns1__DocumentFile(struct soap*, const char*, struct ns1__DocumentFile *, const char*);

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Reason
#define SOAP_TYPE_PointerToSOAP_ENV__Reason (118)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Reason(struct soap*, const char *, int, struct SOAP_ENV__Reason *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Reason(struct soap*, struct SOAP_ENV__Reason **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Reason ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Reason(struct soap*, const char*, struct SOAP_ENV__Reason **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Detail
#define SOAP_TYPE_PointerToSOAP_ENV__Detail (117)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Detail(struct soap*, const char *, int, struct SOAP_ENV__Detail *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Detail(struct soap*, struct SOAP_ENV__Detail **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Detail ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Detail(struct soap*, const char*, struct SOAP_ENV__Detail **, const char*);

#endif

#ifndef WITH_NOGLOBAL

#ifndef SOAP_TYPE_PointerToSOAP_ENV__Code
#define SOAP_TYPE_PointerToSOAP_ENV__Code (111)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToSOAP_ENV__Code(struct soap*, const char *, int, struct SOAP_ENV__Code *const*, const char *);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_get_PointerToSOAP_ENV__Code(struct soap*, struct SOAP_ENV__Code **, const char*, const char*);
SOAP_FMAC3 struct SOAP_ENV__Code ** SOAP_FMAC4 soap_in_PointerToSOAP_ENV__Code(struct soap*, const char*, struct SOAP_ENV__Code **, const char*);

#endif

#ifndef SOAP_TYPE_PointerTons2__removeSenderResponse
#define SOAP_TYPE_PointerTons2__removeSenderResponse (106)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__removeSenderResponse(struct soap*, struct ns2__removeSenderResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__removeSenderResponse(struct soap*, struct ns2__removeSenderResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__removeSenderResponse(struct soap*, const char *, int, struct ns2__removeSenderResponse *const*, const char *);
SOAP_FMAC3 struct ns2__removeSenderResponse ** SOAP_FMAC4 soap_get_PointerTons2__removeSenderResponse(struct soap*, struct ns2__removeSenderResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__removeSenderResponse ** SOAP_FMAC4 soap_in_PointerTons2__removeSenderResponse(struct soap*, const char*, struct ns2__removeSenderResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__RemoveSenderReturnObject
#define SOAP_TYPE_PointerTons1__RemoveSenderReturnObject (105)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__RemoveSenderReturnObject(struct soap*, struct ns1__RemoveSenderReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__RemoveSenderReturnObject(struct soap*, struct ns1__RemoveSenderReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__RemoveSenderReturnObject(struct soap*, const char *, int, struct ns1__RemoveSenderReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__RemoveSenderReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__RemoveSenderReturnObject(struct soap*, struct ns1__RemoveSenderReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__RemoveSenderReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__RemoveSenderReturnObject(struct soap*, const char*, struct ns1__RemoveSenderReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__verifySenderResponse
#define SOAP_TYPE_PointerTons2__verifySenderResponse (101)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__verifySenderResponse(struct soap*, struct ns2__verifySenderResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__verifySenderResponse(struct soap*, struct ns2__verifySenderResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__verifySenderResponse(struct soap*, const char *, int, struct ns2__verifySenderResponse *const*, const char *);
SOAP_FMAC3 struct ns2__verifySenderResponse ** SOAP_FMAC4 soap_get_PointerTons2__verifySenderResponse(struct soap*, struct ns2__verifySenderResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__verifySenderResponse ** SOAP_FMAC4 soap_in_PointerTons2__verifySenderResponse(struct soap*, const char*, struct ns2__verifySenderResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__VerifySenderReturnObject
#define SOAP_TYPE_PointerTons1__VerifySenderReturnObject (100)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__VerifySenderReturnObject(struct soap*, struct ns1__VerifySenderReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__VerifySenderReturnObject(struct soap*, struct ns1__VerifySenderReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__VerifySenderReturnObject(struct soap*, const char *, int, struct ns1__VerifySenderReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__VerifySenderReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__VerifySenderReturnObject(struct soap*, struct ns1__VerifySenderReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__VerifySenderReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__VerifySenderReturnObject(struct soap*, const char*, struct ns1__VerifySenderReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__addSenderResponse
#define SOAP_TYPE_PointerTons2__addSenderResponse (96)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__addSenderResponse(struct soap*, struct ns2__addSenderResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__addSenderResponse(struct soap*, struct ns2__addSenderResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__addSenderResponse(struct soap*, const char *, int, struct ns2__addSenderResponse *const*, const char *);
SOAP_FMAC3 struct ns2__addSenderResponse ** SOAP_FMAC4 soap_get_PointerTons2__addSenderResponse(struct soap*, struct ns2__addSenderResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__addSenderResponse ** SOAP_FMAC4 soap_in_PointerTons2__addSenderResponse(struct soap*, const char*, struct ns2__addSenderResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__SenderData
#define SOAP_TYPE_PointerTons1__SenderData (95)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__SenderData(struct soap*, struct ns1__SenderData *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__SenderData(struct soap*, struct ns1__SenderData *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__SenderData(struct soap*, const char *, int, struct ns1__SenderData *const*, const char *);
SOAP_FMAC3 struct ns1__SenderData ** SOAP_FMAC4 soap_get_PointerTons1__SenderData(struct soap*, struct ns1__SenderData **, const char*, const char*);
SOAP_FMAC3 struct ns1__SenderData ** SOAP_FMAC4 soap_in_PointerTons1__SenderData(struct soap*, const char*, struct ns1__SenderData **, const char*);

#ifndef SOAP_TYPE_PointerTons1__AddSenderReturnObject
#define SOAP_TYPE_PointerTons1__AddSenderReturnObject (94)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__AddSenderReturnObject(struct soap*, struct ns1__AddSenderReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__AddSenderReturnObject(struct soap*, struct ns1__AddSenderReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__AddSenderReturnObject(struct soap*, const char *, int, struct ns1__AddSenderReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__AddSenderReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__AddSenderReturnObject(struct soap*, struct ns1__AddSenderReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__AddSenderReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__AddSenderReturnObject(struct soap*, const char*, struct ns1__AddSenderReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__getPriceResponse
#define SOAP_TYPE_PointerTons2__getPriceResponse (90)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getPriceResponse(struct soap*, struct ns2__getPriceResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getPriceResponse(struct soap*, struct ns2__getPriceResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getPriceResponse(struct soap*, const char *, int, struct ns2__getPriceResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getPriceResponse ** SOAP_FMAC4 soap_get_PointerTons2__getPriceResponse(struct soap*, struct ns2__getPriceResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__getPriceResponse ** SOAP_FMAC4 soap_in_PointerTons2__getPriceResponse(struct soap*, const char*, struct ns2__getPriceResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__PriceReturnObject
#define SOAP_TYPE_PointerTons1__PriceReturnObject (89)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__PriceReturnObject(struct soap*, struct ns1__PriceReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__PriceReturnObject(struct soap*, struct ns1__PriceReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__PriceReturnObject(struct soap*, const char *, int, struct ns1__PriceReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__PriceReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__PriceReturnObject(struct soap*, struct ns1__PriceReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__PriceReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__PriceReturnObject(struct soap*, const char*, struct ns1__PriceReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__getCertificateResponse
#define SOAP_TYPE_PointerTons2__getCertificateResponse (85)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getCertificateResponse(struct soap*, struct ns2__getCertificateResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getCertificateResponse(struct soap*, struct ns2__getCertificateResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getCertificateResponse(struct soap*, const char *, int, struct ns2__getCertificateResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getCertificateResponse ** SOAP_FMAC4 soap_get_PointerTons2__getCertificateResponse(struct soap*, struct ns2__getCertificateResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__getCertificateResponse ** SOAP_FMAC4 soap_in_PointerTons2__getCertificateResponse(struct soap*, const char*, struct ns2__getCertificateResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__CertificateReturnObject
#define SOAP_TYPE_PointerTons1__CertificateReturnObject (84)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__CertificateReturnObject(struct soap*, struct ns1__CertificateReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__CertificateReturnObject(struct soap*, struct ns1__CertificateReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__CertificateReturnObject(struct soap*, const char *, int, struct ns1__CertificateReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__CertificateReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__CertificateReturnObject(struct soap*, struct ns1__CertificateReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__CertificateReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__CertificateReturnObject(struct soap*, const char*, struct ns1__CertificateReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__getSendersResponse
#define SOAP_TYPE_PointerTons2__getSendersResponse (80)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getSendersResponse(struct soap*, struct ns2__getSendersResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getSendersResponse(struct soap*, struct ns2__getSendersResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getSendersResponse(struct soap*, const char *, int, struct ns2__getSendersResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getSendersResponse ** SOAP_FMAC4 soap_get_PointerTons2__getSendersResponse(struct soap*, struct ns2__getSendersResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__getSendersResponse ** SOAP_FMAC4 soap_in_PointerTons2__getSendersResponse(struct soap*, const char*, struct ns2__getSendersResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__SendersReturnObject
#define SOAP_TYPE_PointerTons1__SendersReturnObject (79)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__SendersReturnObject(struct soap*, struct ns1__SendersReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__SendersReturnObject(struct soap*, struct ns1__SendersReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__SendersReturnObject(struct soap*, const char *, int, struct ns1__SendersReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__SendersReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__SendersReturnObject(struct soap*, struct ns1__SendersReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__SendersReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__SendersReturnObject(struct soap*, const char*, struct ns1__SendersReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__getConfigProfilesResponse
#define SOAP_TYPE_PointerTons2__getConfigProfilesResponse (75)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getConfigProfilesResponse(struct soap*, struct ns2__getConfigProfilesResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getConfigProfilesResponse(struct soap*, struct ns2__getConfigProfilesResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getConfigProfilesResponse(struct soap*, const char *, int, struct ns2__getConfigProfilesResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getConfigProfilesResponse ** SOAP_FMAC4 soap_get_PointerTons2__getConfigProfilesResponse(struct soap*, struct ns2__getConfigProfilesResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__getConfigProfilesResponse ** SOAP_FMAC4 soap_in_PointerTons2__getConfigProfilesResponse(struct soap*, const char*, struct ns2__getConfigProfilesResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__ConfigProfilesReturnObject
#define SOAP_TYPE_PointerTons1__ConfigProfilesReturnObject (74)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ConfigProfilesReturnObject(struct soap*, struct ns1__ConfigProfilesReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ConfigProfilesReturnObject(struct soap*, struct ns1__ConfigProfilesReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ConfigProfilesReturnObject(struct soap*, const char *, int, struct ns1__ConfigProfilesReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__ConfigProfilesReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__ConfigProfilesReturnObject(struct soap*, struct ns1__ConfigProfilesReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__ConfigProfilesReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__ConfigProfilesReturnObject(struct soap*, const char*, struct ns1__ConfigProfilesReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__getBalanceResponse
#define SOAP_TYPE_PointerTons2__getBalanceResponse (70)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getBalanceResponse(struct soap*, struct ns2__getBalanceResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getBalanceResponse(struct soap*, struct ns2__getBalanceResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getBalanceResponse(struct soap*, const char *, int, struct ns2__getBalanceResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getBalanceResponse ** SOAP_FMAC4 soap_get_PointerTons2__getBalanceResponse(struct soap*, struct ns2__getBalanceResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__getBalanceResponse ** SOAP_FMAC4 soap_in_PointerTons2__getBalanceResponse(struct soap*, const char*, struct ns2__getBalanceResponse **, const char*);

#ifndef SOAP_TYPE_PointerTons1__BalanceReturnObject
#define SOAP_TYPE_PointerTons1__BalanceReturnObject (69)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__BalanceReturnObject(struct soap*, struct ns1__BalanceReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__BalanceReturnObject(struct soap*, struct ns1__BalanceReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__BalanceReturnObject(struct soap*, const char *, int, struct ns1__BalanceReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__BalanceReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__BalanceReturnObject(struct soap*, struct ns1__BalanceReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__BalanceReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__BalanceReturnObject(struct soap*, const char*, struct ns1__BalanceReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerTons2__getDispatchStatusResponse
#define SOAP_TYPE_PointerTons2__getDispatchStatusResponse (65)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__getDispatchStatusResponse(struct soap*, struct ns2__getDispatchStatusResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__getDispatchStatusResponse(struct soap*, struct ns2__getDispatchStatusResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__getDispatchStatusResponse(struct soap*, const char *, int, struct ns2__getDispatchStatusResponse *const*, const char *);
SOAP_FMAC3 struct ns2__getDispatchStatusResponse ** SOAP_FMAC4 soap_get_PointerTons2__getDispatchStatusResponse(struct soap*, struct ns2__getDispatchStatusResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__getDispatchStatusResponse ** SOAP_FMAC4 soap_in_PointerTons2__getDispatchStatusResponse(struct soap*, const char*, struct ns2__getDispatchStatusResponse **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfDispatchIds
#define SOAP_TYPE_PointerToArrayOfDispatchIds (64)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfDispatchIds(struct soap*, struct ArrayOfDispatchIds *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfDispatchIds(struct soap*, struct ArrayOfDispatchIds *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfDispatchIds(struct soap*, const char *, int, struct ArrayOfDispatchIds *const*, const char *);
SOAP_FMAC3 struct ArrayOfDispatchIds ** SOAP_FMAC4 soap_get_PointerToArrayOfDispatchIds(struct soap*, struct ArrayOfDispatchIds **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfDispatchIds ** SOAP_FMAC4 soap_in_PointerToArrayOfDispatchIds(struct soap*, const char*, struct ArrayOfDispatchIds **, const char*);

#ifndef SOAP_TYPE_PointerTons2__dispatchResponse
#define SOAP_TYPE_PointerTons2__dispatchResponse (60)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons2__dispatchResponse(struct soap*, struct ns2__dispatchResponse *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons2__dispatchResponse(struct soap*, struct ns2__dispatchResponse *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons2__dispatchResponse(struct soap*, const char *, int, struct ns2__dispatchResponse *const*, const char *);
SOAP_FMAC3 struct ns2__dispatchResponse ** SOAP_FMAC4 soap_get_PointerTons2__dispatchResponse(struct soap*, struct ns2__dispatchResponse **, const char*, const char*);
SOAP_FMAC3 struct ns2__dispatchResponse ** SOAP_FMAC4 soap_in_PointerTons2__dispatchResponse(struct soap*, const char*, struct ns2__dispatchResponse **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfOptions
#define SOAP_TYPE_PointerToArrayOfOptions (59)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfOptions(struct soap*, struct ArrayOfOptions *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfOptions(struct soap*, struct ArrayOfOptions *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfOptions(struct soap*, const char *, int, struct ArrayOfOptions *const*, const char *);
SOAP_FMAC3 struct ArrayOfOptions ** SOAP_FMAC4 soap_get_PointerToArrayOfOptions(struct soap*, struct ArrayOfOptions **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfOptions ** SOAP_FMAC4 soap_in_PointerToArrayOfOptions(struct soap*, const char*, struct ArrayOfOptions **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfRecipients
#define SOAP_TYPE_PointerToArrayOfRecipients (58)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfRecipients(struct soap*, struct ArrayOfRecipients *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfRecipients(struct soap*, struct ArrayOfRecipients *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfRecipients(struct soap*, const char *, int, struct ArrayOfRecipients *const*, const char *);
SOAP_FMAC3 struct ArrayOfRecipients ** SOAP_FMAC4 soap_get_PointerToArrayOfRecipients(struct soap*, struct ArrayOfRecipients **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfRecipients ** SOAP_FMAC4 soap_in_PointerToArrayOfRecipients(struct soap*, const char*, struct ArrayOfRecipients **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfDocumentFiles
#define SOAP_TYPE_PointerToArrayOfDocumentFiles (57)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfDocumentFiles(struct soap*, struct ArrayOfDocumentFiles *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfDocumentFiles(struct soap*, struct ArrayOfDocumentFiles *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfDocumentFiles(struct soap*, const char *, int, struct ArrayOfDocumentFiles *const*, const char *);
SOAP_FMAC3 struct ArrayOfDocumentFiles ** SOAP_FMAC4 soap_get_PointerToArrayOfDocumentFiles(struct soap*, struct ArrayOfDocumentFiles **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfDocumentFiles ** SOAP_FMAC4 soap_in_PointerToArrayOfDocumentFiles(struct soap*, const char*, struct ArrayOfDocumentFiles **, const char*);

#ifndef SOAP_TYPE_PointerTons1__DispatchReturnObject
#define SOAP_TYPE_PointerTons1__DispatchReturnObject (56)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DispatchReturnObject(struct soap*, struct ns1__DispatchReturnObject *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DispatchReturnObject(struct soap*, struct ns1__DispatchReturnObject *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DispatchReturnObject(struct soap*, const char *, int, struct ns1__DispatchReturnObject *const*, const char *);
SOAP_FMAC3 struct ns1__DispatchReturnObject ** SOAP_FMAC4 soap_get_PointerTons1__DispatchReturnObject(struct soap*, struct ns1__DispatchReturnObject **, const char*, const char*);
SOAP_FMAC3 struct ns1__DispatchReturnObject ** SOAP_FMAC4 soap_in_PointerTons1__DispatchReturnObject(struct soap*, const char*, struct ns1__DispatchReturnObject **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__ShipmentPrice
#define SOAP_TYPE_PointerToPointerTons1__ShipmentPrice (54)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__ShipmentPrice(struct soap*, const char *, int, struct ns1__ShipmentPrice **const*, const char *);
SOAP_FMAC3 struct ns1__ShipmentPrice *** SOAP_FMAC4 soap_get_PointerToPointerTons1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice ***, const char*, const char*);
SOAP_FMAC3 struct ns1__ShipmentPrice *** SOAP_FMAC4 soap_in_PointerToPointerTons1__ShipmentPrice(struct soap*, const char*, struct ns1__ShipmentPrice ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__ShipmentPrice
#define SOAP_TYPE_PointerTons1__ShipmentPrice (53)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ShipmentPrice(struct soap*, const char *, int, struct ns1__ShipmentPrice *const*, const char *);
SOAP_FMAC3 struct ns1__ShipmentPrice ** SOAP_FMAC4 soap_get_PointerTons1__ShipmentPrice(struct soap*, struct ns1__ShipmentPrice **, const char*, const char*);
SOAP_FMAC3 struct ns1__ShipmentPrice ** SOAP_FMAC4 soap_in_PointerTons1__ShipmentPrice(struct soap*, const char*, struct ns1__ShipmentPrice **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__Sender
#define SOAP_TYPE_PointerToPointerTons1__Sender (52)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__Sender(struct soap*, struct ns1__Sender **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__Sender(struct soap*, struct ns1__Sender **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__Sender(struct soap*, const char *, int, struct ns1__Sender **const*, const char *);
SOAP_FMAC3 struct ns1__Sender *** SOAP_FMAC4 soap_get_PointerToPointerTons1__Sender(struct soap*, struct ns1__Sender ***, const char*, const char*);
SOAP_FMAC3 struct ns1__Sender *** SOAP_FMAC4 soap_in_PointerToPointerTons1__Sender(struct soap*, const char*, struct ns1__Sender ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__Sender
#define SOAP_TYPE_PointerTons1__Sender (51)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Sender(struct soap*, struct ns1__Sender *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Sender(struct soap*, struct ns1__Sender *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Sender(struct soap*, const char *, int, struct ns1__Sender *const*, const char *);
SOAP_FMAC3 struct ns1__Sender ** SOAP_FMAC4 soap_get_PointerTons1__Sender(struct soap*, struct ns1__Sender **, const char*, const char*);
SOAP_FMAC3 struct ns1__Sender ** SOAP_FMAC4 soap_in_PointerTons1__Sender(struct soap*, const char*, struct ns1__Sender **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__ConfigProfile
#define SOAP_TYPE_PointerToPointerTons1__ConfigProfile (50)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__ConfigProfile(struct soap*, struct ns1__ConfigProfile **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__ConfigProfile(struct soap*, struct ns1__ConfigProfile **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__ConfigProfile(struct soap*, const char *, int, struct ns1__ConfigProfile **const*, const char *);
SOAP_FMAC3 struct ns1__ConfigProfile *** SOAP_FMAC4 soap_get_PointerToPointerTons1__ConfigProfile(struct soap*, struct ns1__ConfigProfile ***, const char*, const char*);
SOAP_FMAC3 struct ns1__ConfigProfile *** SOAP_FMAC4 soap_in_PointerToPointerTons1__ConfigProfile(struct soap*, const char*, struct ns1__ConfigProfile ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__ConfigProfile
#define SOAP_TYPE_PointerTons1__ConfigProfile (49)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__ConfigProfile(struct soap*, struct ns1__ConfigProfile *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__ConfigProfile(struct soap*, struct ns1__ConfigProfile *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__ConfigProfile(struct soap*, const char *, int, struct ns1__ConfigProfile *const*, const char *);
SOAP_FMAC3 struct ns1__ConfigProfile ** SOAP_FMAC4 soap_get_PointerTons1__ConfigProfile(struct soap*, struct ns1__ConfigProfile **, const char*, const char*);
SOAP_FMAC3 struct ns1__ConfigProfile ** SOAP_FMAC4 soap_in_PointerTons1__ConfigProfile(struct soap*, const char*, struct ns1__ConfigProfile **, const char*);

#ifndef SOAP_TYPE_PointerTostring
#define SOAP_TYPE_PointerTostring (48)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTostring(struct soap*, char **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTostring(struct soap*, char **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTostring(struct soap*, const char *, int, char **const*, const char *);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_get_PointerTostring(struct soap*, char ***, const char*, const char*);
SOAP_FMAC3 char *** SOAP_FMAC4 soap_in_PointerTostring(struct soap*, const char*, char ***, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__Shipment
#define SOAP_TYPE_PointerToPointerTons1__Shipment (46)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__Shipment(struct soap*, struct ns1__Shipment **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__Shipment(struct soap*, struct ns1__Shipment **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__Shipment(struct soap*, const char *, int, struct ns1__Shipment **const*, const char *);
SOAP_FMAC3 struct ns1__Shipment *** SOAP_FMAC4 soap_get_PointerToPointerTons1__Shipment(struct soap*, struct ns1__Shipment ***, const char*, const char*);
SOAP_FMAC3 struct ns1__Shipment *** SOAP_FMAC4 soap_in_PointerToPointerTons1__Shipment(struct soap*, const char*, struct ns1__Shipment ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__Shipment
#define SOAP_TYPE_PointerTons1__Shipment (45)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Shipment(struct soap*, struct ns1__Shipment *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Shipment(struct soap*, struct ns1__Shipment *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Shipment(struct soap*, const char *, int, struct ns1__Shipment *const*, const char *);
SOAP_FMAC3 struct ns1__Shipment ** SOAP_FMAC4 soap_get_PointerTons1__Shipment(struct soap*, struct ns1__Shipment **, const char*, const char*);
SOAP_FMAC3 struct ns1__Shipment ** SOAP_FMAC4 soap_in_PointerTons1__Shipment(struct soap*, const char*, struct ns1__Shipment **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__Option
#define SOAP_TYPE_PointerToPointerTons1__Option (44)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__Option(struct soap*, struct ns1__Option **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__Option(struct soap*, struct ns1__Option **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__Option(struct soap*, const char *, int, struct ns1__Option **const*, const char *);
SOAP_FMAC3 struct ns1__Option *** SOAP_FMAC4 soap_get_PointerToPointerTons1__Option(struct soap*, struct ns1__Option ***, const char*, const char*);
SOAP_FMAC3 struct ns1__Option *** SOAP_FMAC4 soap_in_PointerToPointerTons1__Option(struct soap*, const char*, struct ns1__Option ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__Option
#define SOAP_TYPE_PointerTons1__Option (43)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Option(struct soap*, struct ns1__Option *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Option(struct soap*, struct ns1__Option *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Option(struct soap*, const char *, int, struct ns1__Option *const*, const char *);
SOAP_FMAC3 struct ns1__Option ** SOAP_FMAC4 soap_get_PointerTons1__Option(struct soap*, struct ns1__Option **, const char*, const char*);
SOAP_FMAC3 struct ns1__Option ** SOAP_FMAC4 soap_in_PointerTons1__Option(struct soap*, const char*, struct ns1__Option **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__Recipient
#define SOAP_TYPE_PointerToPointerTons1__Recipient (41)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__Recipient(struct soap*, struct ns1__Recipient **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__Recipient(struct soap*, struct ns1__Recipient **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__Recipient(struct soap*, const char *, int, struct ns1__Recipient **const*, const char *);
SOAP_FMAC3 struct ns1__Recipient *** SOAP_FMAC4 soap_get_PointerToPointerTons1__Recipient(struct soap*, struct ns1__Recipient ***, const char*, const char*);
SOAP_FMAC3 struct ns1__Recipient *** SOAP_FMAC4 soap_in_PointerToPointerTons1__Recipient(struct soap*, const char*, struct ns1__Recipient ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__Recipient
#define SOAP_TYPE_PointerTons1__Recipient (40)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__Recipient(struct soap*, struct ns1__Recipient *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__Recipient(struct soap*, struct ns1__Recipient *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__Recipient(struct soap*, const char *, int, struct ns1__Recipient *const*, const char *);
SOAP_FMAC3 struct ns1__Recipient ** SOAP_FMAC4 soap_get_PointerTons1__Recipient(struct soap*, struct ns1__Recipient **, const char*, const char*);
SOAP_FMAC3 struct ns1__Recipient ** SOAP_FMAC4 soap_in_PointerTons1__Recipient(struct soap*, const char*, struct ns1__Recipient **, const char*);

#ifndef SOAP_TYPE_PointerToPointerTons1__DocumentFile
#define SOAP_TYPE_PointerToPointerTons1__DocumentFile (38)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToPointerTons1__DocumentFile(struct soap*, struct ns1__DocumentFile **const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToPointerTons1__DocumentFile(struct soap*, struct ns1__DocumentFile **const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToPointerTons1__DocumentFile(struct soap*, const char *, int, struct ns1__DocumentFile **const*, const char *);
SOAP_FMAC3 struct ns1__DocumentFile *** SOAP_FMAC4 soap_get_PointerToPointerTons1__DocumentFile(struct soap*, struct ns1__DocumentFile ***, const char*, const char*);
SOAP_FMAC3 struct ns1__DocumentFile *** SOAP_FMAC4 soap_in_PointerToPointerTons1__DocumentFile(struct soap*, const char*, struct ns1__DocumentFile ***, const char*);

#ifndef SOAP_TYPE_PointerTons1__DocumentFile
#define SOAP_TYPE_PointerTons1__DocumentFile (37)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTons1__DocumentFile(struct soap*, struct ns1__DocumentFile *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTons1__DocumentFile(struct soap*, struct ns1__DocumentFile *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTons1__DocumentFile(struct soap*, const char *, int, struct ns1__DocumentFile *const*, const char *);
SOAP_FMAC3 struct ns1__DocumentFile ** SOAP_FMAC4 soap_get_PointerTons1__DocumentFile(struct soap*, struct ns1__DocumentFile **, const char*, const char*);
SOAP_FMAC3 struct ns1__DocumentFile ** SOAP_FMAC4 soap_in_PointerTons1__DocumentFile(struct soap*, const char*, struct ns1__DocumentFile **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfShipmentsPrice
#define SOAP_TYPE_PointerToArrayOfShipmentsPrice (32)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfShipmentsPrice(struct soap*, struct ArrayOfShipmentsPrice *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfShipmentsPrice(struct soap*, struct ArrayOfShipmentsPrice *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfShipmentsPrice(struct soap*, const char *, int, struct ArrayOfShipmentsPrice *const*, const char *);
SOAP_FMAC3 struct ArrayOfShipmentsPrice ** SOAP_FMAC4 soap_get_PointerToArrayOfShipmentsPrice(struct soap*, struct ArrayOfShipmentsPrice **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfShipmentsPrice ** SOAP_FMAC4 soap_in_PointerToArrayOfShipmentsPrice(struct soap*, const char*, struct ArrayOfShipmentsPrice **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfSenders
#define SOAP_TYPE_PointerToArrayOfSenders (28)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfSenders(struct soap*, struct ArrayOfSenders *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfSenders(struct soap*, struct ArrayOfSenders *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfSenders(struct soap*, const char *, int, struct ArrayOfSenders *const*, const char *);
SOAP_FMAC3 struct ArrayOfSenders ** SOAP_FMAC4 soap_get_PointerToArrayOfSenders(struct soap*, struct ArrayOfSenders **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfSenders ** SOAP_FMAC4 soap_in_PointerToArrayOfSenders(struct soap*, const char*, struct ArrayOfSenders **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfConfigProfiles
#define SOAP_TYPE_PointerToArrayOfConfigProfiles (25)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfConfigProfiles(struct soap*, struct ArrayOfConfigProfiles *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfConfigProfiles(struct soap*, struct ArrayOfConfigProfiles *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfConfigProfiles(struct soap*, const char *, int, struct ArrayOfConfigProfiles *const*, const char *);
SOAP_FMAC3 struct ArrayOfConfigProfiles ** SOAP_FMAC4 soap_get_PointerToArrayOfConfigProfiles(struct soap*, struct ArrayOfConfigProfiles **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfConfigProfiles ** SOAP_FMAC4 soap_in_PointerToArrayOfConfigProfiles(struct soap*, const char*, struct ArrayOfConfigProfiles **, const char*);

#ifndef SOAP_TYPE_PointerToArrayOfShipments
#define SOAP_TYPE_PointerToArrayOfShipments (21)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToArrayOfShipments(struct soap*, struct ArrayOfShipments *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToArrayOfShipments(struct soap*, struct ArrayOfShipments *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToArrayOfShipments(struct soap*, const char *, int, struct ArrayOfShipments *const*, const char *);
SOAP_FMAC3 struct ArrayOfShipments ** SOAP_FMAC4 soap_get_PointerToArrayOfShipments(struct soap*, struct ArrayOfShipments **, const char*, const char*);
SOAP_FMAC3 struct ArrayOfShipments ** SOAP_FMAC4 soap_in_PointerToArrayOfShipments(struct soap*, const char*, struct ArrayOfShipments **, const char*);

#ifndef SOAP_TYPE_PointerTofloat
#define SOAP_TYPE_PointerTofloat (14)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerTofloat(struct soap*, float *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerTofloat(struct soap*, float *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerTofloat(struct soap*, const char *, int, float *const*, const char *);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_get_PointerTofloat(struct soap*, float **, const char*, const char*);
SOAP_FMAC3 float ** SOAP_FMAC4 soap_in_PointerTofloat(struct soap*, const char*, float **, const char*);

#ifndef SOAP_TYPE_PointerToint
#define SOAP_TYPE_PointerToint (10)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_PointerToint(struct soap*, int *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_PointerToint(struct soap*, int *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_PointerToint(struct soap*, const char *, int, int *const*, const char *);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_get_PointerToint(struct soap*, int **, const char*, const char*);
SOAP_FMAC3 int ** SOAP_FMAC4 soap_in_PointerToint(struct soap*, const char*, int **, const char*);

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
#endif

#define soap_default__QName(soap, a) soap_default_string(soap, a)


#define soap_serialize__QName(soap, a) soap_serialize_string(soap, a)

SOAP_FMAC3 int SOAP_FMAC4 soap_put__QName(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out__QName(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get__QName(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in__QName(struct soap*, const char*, char **, const char*);

#ifndef SOAP_TYPE_string
#define SOAP_TYPE_string (4)
#endif
SOAP_FMAC3 void SOAP_FMAC4 soap_default_string(struct soap*, char **);
SOAP_FMAC3 void SOAP_FMAC4 soap_serialize_string(struct soap*, char *const*);
SOAP_FMAC3 int SOAP_FMAC4 soap_put_string(struct soap*, char *const*, const char*, const char*);
SOAP_FMAC3 int SOAP_FMAC4 soap_out_string(struct soap*, const char*, int, char*const*, const char*);
SOAP_FMAC3 char ** SOAP_FMAC4 soap_get_string(struct soap*, char **, const char*, const char*);
SOAP_FMAC3 char * * SOAP_FMAC4 soap_in_string(struct soap*, const char*, char **, const char*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapH.h */
