/* soapStub.h
   Generated by gSOAP 2.7.13 from postivoService.h
   Copyright(C) 2000-2009, Robert van Engelen, Genivia Inc. All Rights Reserved.
   This part of the software is released under one of the following licenses:
   GPL, the gSOAP public license, or Genivia's license for commercial use.
*/

#ifndef soapStub_H
#define soapStub_H
#include "stdsoap2.h"
#ifdef __cplusplus
extern "C" {
#endif

/******************************************************************************\
 *                                                                            *
 * Types with Custom Serializers                                              *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Enumerations                                                               *
 *                                                                            *
\******************************************************************************/


#ifndef SOAP_TYPE_xsd__boolean
#define SOAP_TYPE_xsd__boolean (7)
/* xsd:boolean */
enum xsd__boolean {xsd__boolean__false_ = 0, xsd__boolean__true_ = 1};
#endif

/******************************************************************************\
 *                                                                            *
 * Classes and Structs                                                        *
 *                                                                            *
\******************************************************************************/


#if 0 /* volatile type: do not redeclare here */

#endif

#ifndef SOAP_TYPE_ns1__DocumentFile
#define SOAP_TYPE_ns1__DocumentFile (8)
/* ns1:DocumentFile */
struct ns1__DocumentFile
{
	char *file_USCOREstream;	/* required element of type xsd:string */
	char *file_USCOREname;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__Recipient
#define SOAP_TYPE_ns1__Recipient (9)
/* ns1:Recipient */
struct ns1__Recipient
{
	char *source;	/* optional element of type xsd:string */
	int *id;	/* optional element of type xsd:int */
	char *recipient_USCOREname;	/* optional element of type xsd:string */
	char *recipient_USCOREaddress_USCOREprefix;	/* optional element of type xsd:string */
	char *recipient_USCOREaddress;	/* optional element of type xsd:string */
	char *recipient_USCOREhome_USCOREnumber;	/* optional element of type xsd:string */
	char *recipient_USCOREflat_USCOREnumber;	/* optional element of type xsd:string */
	char *recipient_USCOREpost_USCOREcode;	/* optional element of type xsd:string */
	char *recipient_USCOREcity;	/* optional element of type xsd:string */
	char *recipient_USCOREcountry;	/* optional element of type xsd:string */
	char *recipient_USCOREfax_USCOREnumber;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__Option
#define SOAP_TYPE_ns1__Option (11)
/* ns1:Option */
struct ns1__Option
{
	char *name;	/* required element of type xsd:string */
	char *value;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__Shipment
#define SOAP_TYPE_ns1__Shipment (12)
/* ns1:Shipment */
struct ns1__Shipment
{
	char *id;	/* optional element of type xsd:string */
	char *custom_USCOREid;	/* optional element of type xsd:string */
	char *recipient_USCOREname;	/* optional element of type xsd:string */
	char *recipient_USCOREaddress;	/* optional element of type xsd:string */
	char *recipient_USCOREhome_USCOREnumber;	/* optional element of type xsd:string */
	char *recipient_USCOREflat_USCOREnumber;	/* optional element of type xsd:string */
	char *recipient_USCOREpost_USCOREcode;	/* optional element of type xsd:string */
	char *recipient_USCOREcity;	/* optional element of type xsd:string */
	char *recipient_USCOREcountry;	/* optional element of type xsd:string */
	char *recipient_USCOREfax_USCOREnumber;	/* optional element of type xsd:string */
	char *dispatch_USCOREcarrier;	/* optional element of type xsd:string */
	char *dispatch_USCOREtype;	/* optional element of type xsd:string */
	int *page_USCOREnumber;	/* optional element of type xsd:int */
	float *price;	/* optional element of type xsd:float */
	char *status;	/* optional element of type xsd:string */
	char *status_USCOREcode;	/* optional element of type xsd:string */
	char *status_USCOREdescription;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ConfigProfile
#define SOAP_TYPE_ns1__ConfigProfile (15)
/* ns1:ConfigProfile */
struct ns1__ConfigProfile
{
	int *config_USCOREid;	/* optional element of type xsd:int */
	char *config_USCOREname;	/* optional element of type xsd:string */
	char *paper_USCOREtype;	/* optional element of type xsd:string */
	char *paper_USCOREprint_USCOREtype;	/* optional element of type xsd:string */
	char *envelope_USCOREtype;	/* optional element of type xsd:string */
	char *envelope_USCOREtemplate;	/* optional element of type xsd:string */
	char *envelope_USCOREprint_USCOREtype;	/* optional element of type xsd:string */
	char *carrier;	/* optional element of type xsd:string */
	char *dispatch_USCOREtype;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__Sender
#define SOAP_TYPE_ns1__Sender (16)
/* ns1:Sender */
struct ns1__Sender
{
	int *sender_USCOREid;	/* optional element of type xsd:int */
	char *sender_USCOREname;	/* optional element of type xsd:string */
	char *sender_USCOREaddress;	/* optional element of type xsd:string */
	char *sender_USCOREhome_USCOREnumber;	/* optional element of type xsd:string */
	char *sender_USCOREflat_USCOREnumber;	/* optional element of type xsd:string */
	char *sender_USCOREpost_USCOREcode;	/* optional element of type xsd:string */
	char *sender_USCOREcity;	/* optional element of type xsd:string */
	char *sender_USCOREcountry;	/* optional element of type xsd:string */
	char *sender_USCOREfax_USCOREnumber;	/* optional element of type xsd:string */
	char *default_;	/* optional element of type xsd:string */
	char *active;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__ShipmentPrice
#define SOAP_TYPE_ns1__ShipmentPrice (17)
/* ns1:ShipmentPrice */
struct ns1__ShipmentPrice
{
	char *recipient_USCOREname;	/* optional element of type xsd:string */
	char *recipient_USCOREaddress;	/* optional element of type xsd:string */
	char *recipient_USCOREhome_USCOREnumber;	/* optional element of type xsd:string */
	char *recipient_USCOREflat_USCOREnumber;	/* optional element of type xsd:string */
	char *recipient_USCOREpost_USCOREcode;	/* optional element of type xsd:string */
	char *recipient_USCOREcity;	/* optional element of type xsd:string */
	char *recipient_USCOREcountry;	/* optional element of type xsd:string */
	char *recipient_USCOREfax_USCOREnumber;	/* optional element of type xsd:string */
	char *dispatch_USCOREcarrier;	/* optional element of type xsd:string */
	char *dispatch_USCOREtype;	/* optional element of type xsd:string */
	int *page_USCOREnumber;	/* optional element of type xsd:int */
	float *price;	/* optional element of type xsd:float */
};
#endif

#ifndef SOAP_TYPE_ns1__SenderData
#define SOAP_TYPE_ns1__SenderData (18)
/* ns1:SenderData */
struct ns1__SenderData
{
	char *sender_USCOREname;	/* optional element of type xsd:string */
	char *sender_USCOREaddress_USCOREprefix;	/* optional element of type xsd:string */
	char *sender_USCOREaddress;	/* optional element of type xsd:string */
	char *sender_USCOREhome_USCOREnumber;	/* optional element of type xsd:string */
	char *sender_USCOREflat_USCOREnumber;	/* optional element of type xsd:string */
	char *sender_USCOREpost_USCOREcode;	/* optional element of type xsd:string */
	char *sender_USCOREcity;	/* optional element of type xsd:string */
	char *sender_USCOREcountry;	/* optional element of type xsd:string */
	char *sender_USCOREfax_USCOREnumber;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__DispatchReturnObject
#define SOAP_TYPE_ns1__DispatchReturnObject (19)
/* ns1:DispatchReturnObject */
struct ns1__DispatchReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
	struct ArrayOfShipments *shipments;	/* required element of type ArrayOfShipment */
};
#endif

#ifndef SOAP_TYPE_ns1__BalanceReturnObject
#define SOAP_TYPE_ns1__BalanceReturnObject (22)
/* ns1:BalanceReturnObject */
struct ns1__BalanceReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
	float *balance;	/* optional element of type xsd:float */
	float *limit;	/* optional element of type xsd:float */
	int *postpaid;	/* optional element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns1__ConfigProfilesReturnObject
#define SOAP_TYPE_ns1__ConfigProfilesReturnObject (23)
/* ns1:ConfigProfilesReturnObject */
struct ns1__ConfigProfilesReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
	struct ArrayOfConfigProfiles *config_USCOREprofiles;	/* optional element of type ArrayOfConfigProfile */
};
#endif

#ifndef SOAP_TYPE_ns1__SendersReturnObject
#define SOAP_TYPE_ns1__SendersReturnObject (26)
/* ns1:SendersReturnObject */
struct ns1__SendersReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
	struct ArrayOfSenders *senders;	/* optional element of type ArrayOfSender */
};
#endif

#ifndef SOAP_TYPE_ns1__CertificateReturnObject
#define SOAP_TYPE_ns1__CertificateReturnObject (29)
/* ns1:CertificateReturnObject */
struct ns1__CertificateReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
	enum xsd__boolean cert_USCOREavailable;	/* required element of type xsd:boolean */
	char *cert_USCOREcontent;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__PriceReturnObject
#define SOAP_TYPE_ns1__PriceReturnObject (30)
/* ns1:PriceReturnObject */
struct ns1__PriceReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
	struct ArrayOfShipmentsPrice *shipments_USCOREprice;	/* required element of type ArrayOfShipmentPrice */
};
#endif

#ifndef SOAP_TYPE_ns1__AddSenderReturnObject
#define SOAP_TYPE_ns1__AddSenderReturnObject (33)
/* ns1:AddSenderReturnObject */
struct ns1__AddSenderReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
	int *sender_USCOREid;	/* optional element of type xsd:int */
	char *shipment_USCOREid;	/* optional element of type xsd:string */
	char *sender_USCOREname;	/* optional element of type xsd:string */
	char *sender_USCOREaddress;	/* optional element of type xsd:string */
	char *sender_USCOREhome_USCOREnumber;	/* optional element of type xsd:string */
	char *sender_USCOREflat_USCOREnumber;	/* optional element of type xsd:string */
	char *sender_USCOREpost_USCOREcode;	/* optional element of type xsd:string */
	char *sender_USCOREcity;	/* optional element of type xsd:string */
	char *sender_USCOREcountry;	/* optional element of type xsd:string */
	char *sender_USCOREfax_USCOREnumber;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__VerifySenderReturnObject
#define SOAP_TYPE_ns1__VerifySenderReturnObject (34)
/* ns1:VerifySenderReturnObject */
struct ns1__VerifySenderReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns1__RemoveSenderReturnObject
#define SOAP_TYPE_ns1__RemoveSenderReturnObject (35)
/* ns1:RemoveSenderReturnObject */
struct ns1__RemoveSenderReturnObject
{
	char *result;	/* required element of type xsd:string */
	char *result_USCOREcode;	/* required element of type xsd:string */
	char *result_USCOREdescription;	/* required element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ArrayOfDocumentFiles
#define SOAP_TYPE_ArrayOfDocumentFiles (36)
/* SOAP encoded array of ns1:DocumentFile schema type: */
struct ArrayOfDocumentFiles
{
	struct ns1__DocumentFile **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ArrayOfRecipients
#define SOAP_TYPE_ArrayOfRecipients (39)
/* SOAP encoded array of ns1:Recipient schema type: */
struct ArrayOfRecipients
{
	struct ns1__Recipient **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ArrayOfOptions
#define SOAP_TYPE_ArrayOfOptions (42)
/* SOAP encoded array of ns1:Option schema type: */
struct ArrayOfOptions
{
	struct ns1__Option **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ArrayOfShipments
#define SOAP_TYPE_ArrayOfShipments (20)
/* SOAP encoded array of ns1:Shipment schema type: */
struct ArrayOfShipments
{
	struct ns1__Shipment **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ArrayOfDispatchIds
#define SOAP_TYPE_ArrayOfDispatchIds (47)
/* SOAP encoded array of xsd:string schema type: */
struct ArrayOfDispatchIds
{
	char **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ArrayOfConfigProfiles
#define SOAP_TYPE_ArrayOfConfigProfiles (24)
/* SOAP encoded array of ns1:ConfigProfile schema type: */
struct ArrayOfConfigProfiles
{
	struct ns1__ConfigProfile **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ArrayOfSenders
#define SOAP_TYPE_ArrayOfSenders (27)
/* SOAP encoded array of ns1:Sender schema type: */
struct ArrayOfSenders
{
	struct ns1__Sender **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ArrayOfShipmentsPrice
#define SOAP_TYPE_ArrayOfShipmentsPrice (31)
/* SOAP encoded array of ns1:ShipmentPrice schema type: */
struct ArrayOfShipmentsPrice
{
	struct ns1__ShipmentPrice **__ptr;
	int __size;
};
#endif

#ifndef SOAP_TYPE_ns2__dispatchResponse
#define SOAP_TYPE_ns2__dispatchResponse (55)
/* ns2:dispatchResponse */
struct ns2__dispatchResponse
{
	struct ns1__DispatchReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:DispatchReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__dispatch
#define SOAP_TYPE_ns2__dispatch (62)
/* ns2:dispatch */
struct ns2__dispatch
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	char *msg_USCOREtype;	/* optional element of type xsd:string */
	struct ArrayOfDocumentFiles *document_USCOREfiles;	/* optional element of type ArrayOfDocumentFile */
	struct ArrayOfRecipients *recipients;	/* optional element of type ArrayOfRecipient */
	struct ArrayOfOptions *options;	/* optional element of type ArrayOfOption */
};
#endif

#ifndef SOAP_TYPE_ns2__getDispatchStatusResponse
#define SOAP_TYPE_ns2__getDispatchStatusResponse (63)
/* ns2:getDispatchStatusResponse */
struct ns2__getDispatchStatusResponse
{
	struct ns1__DispatchReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:DispatchReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__getDispatchStatus
#define SOAP_TYPE_ns2__getDispatchStatus (67)
/* ns2:getDispatchStatus */
struct ns2__getDispatchStatus
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	struct ArrayOfDispatchIds *dispatch_USCOREids;	/* optional element of type ArrayOfstring */
};
#endif

#ifndef SOAP_TYPE_ns2__getBalanceResponse
#define SOAP_TYPE_ns2__getBalanceResponse (68)
/* ns2:getBalanceResponse */
struct ns2__getBalanceResponse
{
	struct ns1__BalanceReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:BalanceReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__getBalance
#define SOAP_TYPE_ns2__getBalance (72)
/* ns2:getBalance */
struct ns2__getBalance
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__getConfigProfilesResponse
#define SOAP_TYPE_ns2__getConfigProfilesResponse (73)
/* ns2:getConfigProfilesResponse */
struct ns2__getConfigProfilesResponse
{
	struct ns1__ConfigProfilesReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:ConfigProfilesReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__getConfigProfiles
#define SOAP_TYPE_ns2__getConfigProfiles (77)
/* ns2:getConfigProfiles */
struct ns2__getConfigProfiles
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	char *msg_USCOREtype;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__getSendersResponse
#define SOAP_TYPE_ns2__getSendersResponse (78)
/* ns2:getSendersResponse */
struct ns2__getSendersResponse
{
	struct ns1__SendersReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:SendersReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__getSenders
#define SOAP_TYPE_ns2__getSenders (82)
/* ns2:getSenders */
struct ns2__getSenders
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__getCertificateResponse
#define SOAP_TYPE_ns2__getCertificateResponse (83)
/* ns2:getCertificateResponse */
struct ns2__getCertificateResponse
{
	struct ns1__CertificateReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:CertificateReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__getCertificate
#define SOAP_TYPE_ns2__getCertificate (87)
/* ns2:getCertificate */
struct ns2__getCertificate
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	char *dispatch_USCOREid;	/* optional element of type xsd:string */
	int certificate_USCOREtype;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__getPriceResponse
#define SOAP_TYPE_ns2__getPriceResponse (88)
/* ns2:getPriceResponse */
struct ns2__getPriceResponse
{
	struct ns1__PriceReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:PriceReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__getPrice
#define SOAP_TYPE_ns2__getPrice (92)
/* ns2:getPrice */
struct ns2__getPrice
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	char *msg_USCOREtype;	/* optional element of type xsd:string */
	struct ArrayOfDocumentFiles *document_USCOREfiles;	/* optional element of type ArrayOfDocumentFile */
	struct ArrayOfRecipients *recipients;	/* optional element of type ArrayOfRecipient */
	int config_USCOREid;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_ns2__addSenderResponse
#define SOAP_TYPE_ns2__addSenderResponse (93)
/* ns2:addSenderResponse */
struct ns2__addSenderResponse
{
	struct ns1__AddSenderReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:AddSenderReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__addSender
#define SOAP_TYPE_ns2__addSender (98)
/* ns2:addSender */
struct ns2__addSender
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	struct ns1__SenderData *sender_USCOREdata;	/* optional element of type ns1:SenderData */
	enum xsd__boolean accept_USCOREterms;	/* required element of type xsd:boolean */
};
#endif

#ifndef SOAP_TYPE_ns2__verifySenderResponse
#define SOAP_TYPE_ns2__verifySenderResponse (99)
/* ns2:verifySenderResponse */
struct ns2__verifySenderResponse
{
	struct ns1__VerifySenderReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:VerifySenderReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__verifySender
#define SOAP_TYPE_ns2__verifySender (103)
/* ns2:verifySender */
struct ns2__verifySender
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	int sender_USCOREid;	/* required element of type xsd:int */
	char *verification_USCOREcode;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_ns2__removeSenderResponse
#define SOAP_TYPE_ns2__removeSenderResponse (104)
/* ns2:removeSenderResponse */
struct ns2__removeSenderResponse
{
	struct ns1__RemoveSenderReturnObject *return_;	/* SOAP 1.2 RPC return element (when namespace qualified) */	/* optional element of type ns1:RemoveSenderReturnObject */
};
#endif

#ifndef SOAP_TYPE_ns2__removeSender
#define SOAP_TYPE_ns2__removeSender (108)
/* ns2:removeSender */
struct ns2__removeSender
{
	char *login;	/* optional element of type xsd:string */
	char *api_USCOREpass;	/* optional element of type xsd:string */
	int sender_USCOREid;	/* required element of type xsd:int */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Header
#define SOAP_TYPE_SOAP_ENV__Header (109)
/* SOAP Header: */
struct SOAP_ENV__Header
{
#ifdef WITH_NOEMPTYSTRUCT
	char dummy;	/* dummy member to enable compilation */
#endif
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Code
#define SOAP_TYPE_SOAP_ENV__Code (110)
/* SOAP Fault Code: */
struct SOAP_ENV__Code
{
	char *SOAP_ENV__Value;	/* optional element of type xsd:QName */
	struct SOAP_ENV__Code *SOAP_ENV__Subcode;	/* optional element of type SOAP-ENV:Code */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Detail
#define SOAP_TYPE_SOAP_ENV__Detail (112)
/* SOAP-ENV:Detail */
struct SOAP_ENV__Detail
{
	int __type;	/* any type of element <fault> (defined below) */
	void *fault;	/* transient */
	char *__any;
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Reason
#define SOAP_TYPE_SOAP_ENV__Reason (115)
/* SOAP-ENV:Reason */
struct SOAP_ENV__Reason
{
	char *SOAP_ENV__Text;	/* optional element of type xsd:string */
};
#endif

#ifndef SOAP_TYPE_SOAP_ENV__Fault
#define SOAP_TYPE_SOAP_ENV__Fault (116)
/* SOAP Fault: */
struct SOAP_ENV__Fault
{
	char *faultcode;	/* optional element of type xsd:QName */
	char *faultstring;	/* optional element of type xsd:string */
	char *faultactor;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *detail;	/* optional element of type SOAP-ENV:Detail */
	struct SOAP_ENV__Code *SOAP_ENV__Code;	/* optional element of type SOAP-ENV:Code */
	struct SOAP_ENV__Reason *SOAP_ENV__Reason;	/* optional element of type SOAP-ENV:Reason */
	char *SOAP_ENV__Node;	/* optional element of type xsd:string */
	char *SOAP_ENV__Role;	/* optional element of type xsd:string */
	struct SOAP_ENV__Detail *SOAP_ENV__Detail;	/* optional element of type SOAP-ENV:Detail */
};
#endif

/******************************************************************************\
 *                                                                            *
 * Typedefs                                                                   *
 *                                                                            *
\******************************************************************************/

#ifndef SOAP_TYPE__QName
#define SOAP_TYPE__QName (5)
typedef char *_QName;
#endif

#ifndef SOAP_TYPE__XML
#define SOAP_TYPE__XML (6)
typedef char *_XML;
#endif


/******************************************************************************\
 *                                                                            *
 * Externals                                                                  *
 *                                                                            *
\******************************************************************************/


/******************************************************************************\
 *                                                                            *
 * Service Operations                                                         *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 ns2__dispatch(struct soap*, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, struct ArrayOfOptions *options, struct ns2__dispatchResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 ns2__getDispatchStatus(struct soap*, char *login, char *api_USCOREpass, struct ArrayOfDispatchIds *dispatch_USCOREids, struct ns2__getDispatchStatusResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 ns2__getBalance(struct soap*, char *login, char *api_USCOREpass, struct ns2__getBalanceResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 ns2__getConfigProfiles(struct soap*, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ns2__getConfigProfilesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 ns2__getSenders(struct soap*, char *login, char *api_USCOREpass, struct ns2__getSendersResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 ns2__getCertificate(struct soap*, char *login, char *api_USCOREpass, char *dispatch_USCOREid, int certificate_USCOREtype, struct ns2__getCertificateResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 ns2__getPrice(struct soap*, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, int config_USCOREid, struct ns2__getPriceResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 ns2__addSender(struct soap*, char *login, char *api_USCOREpass, struct ns1__SenderData *sender_USCOREdata, enum xsd__boolean accept_USCOREterms, struct ns2__addSenderResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 ns2__verifySender(struct soap*, char *login, char *api_USCOREpass, int sender_USCOREid, char *verification_USCOREcode, struct ns2__verifySenderResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 ns2__removeSender(struct soap*, char *login, char *api_USCOREpass, int sender_USCOREid, struct ns2__removeSenderResponse *_param_10);

/******************************************************************************\
 *                                                                            *
 * Stubs                                                                      *
 *                                                                            *
\******************************************************************************/


SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__dispatch(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, struct ArrayOfOptions *options, struct ns2__dispatchResponse *_param_1);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getDispatchStatus(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ArrayOfDispatchIds *dispatch_USCOREids, struct ns2__getDispatchStatusResponse *_param_2);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getBalance(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ns2__getBalanceResponse *_param_3);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getConfigProfiles(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ns2__getConfigProfilesResponse *_param_4);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getSenders(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ns2__getSendersResponse *_param_5);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getCertificate(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *dispatch_USCOREid, int certificate_USCOREtype, struct ns2__getCertificateResponse *_param_6);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__getPrice(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, char *msg_USCOREtype, struct ArrayOfDocumentFiles *document_USCOREfiles, struct ArrayOfRecipients *recipients, int config_USCOREid, struct ns2__getPriceResponse *_param_7);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__addSender(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, struct ns1__SenderData *sender_USCOREdata, enum xsd__boolean accept_USCOREterms, struct ns2__addSenderResponse *_param_8);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__verifySender(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, int sender_USCOREid, char *verification_USCOREcode, struct ns2__verifySenderResponse *_param_9);

SOAP_FMAC5 int SOAP_FMAC6 soap_call_ns2__removeSender(struct soap *soap, const char *soap_endpoint, const char *soap_action, char *login, char *api_USCOREpass, int sender_USCOREid, struct ns2__removeSenderResponse *_param_10);

/******************************************************************************\
 *                                                                            *
 * Skeletons                                                                  *
 *                                                                            *
\******************************************************************************/

SOAP_FMAC5 int SOAP_FMAC6 soap_serve(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_request(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__dispatch(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getDispatchStatus(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getBalance(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getConfigProfiles(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getSenders(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getCertificate(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__getPrice(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__addSender(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__verifySender(struct soap*);

SOAP_FMAC5 int SOAP_FMAC6 soap_serve_ns2__removeSender(struct soap*);

#ifdef __cplusplus
}
#endif

#endif

/* End of soapStub.h */
